/** Explicações curtas, contextuais e sem aconselhamento jurídico automatizado. */
export const GLOSSARY=Object.freeze({
 IA:'Inteligência artificial: ajuda a explicar e sugerir alterações, mas o motor matemático realiza os cálculos e você decide o que salvar.',
 INSS:'Instituto Nacional do Seguro Social. Aqui é a contribuição previdenciária descontada do contracheque; a estimativa não substitui o valor oficial.',
 IRRF:'Imposto de Renda Retido na Fonte. Use o valor do contracheque, pois retenções variam conforme a folha e a competência.',
 WFH:'Work from home: rubrica de ajuda de custo para trabalho remoto, quando existir em seu contracheque.',
 RLS:'Row-Level Security: regra do banco que permite a cada conta acessar apenas os próprios registros.',
 TJDFT:'Tribunal de Justiça do Distrito Federal e dos Territórios.',
 CEJUSC:'Centro Judiciário de Solução de Conflitos e Cidadania, que realiza conciliação e tratamento consensual de conflitos.',
 'CEJUSC-SUPER-PRE':'Unidade/procedimento do TJDFT associado ao tratamento de superendividamento. Consulte os documentos do processo para a denominação exata.',
 CDC:'Código de Defesa do Consumidor. A Lei nº 14.181/2021 incluiu disposições sobre prevenção e tratamento do superendividamento.',
 SCR:'Sistema de Informações de Créditos do Banco Central; reúne informações reportadas pelas instituições financeiras.',
 Bacen:'Banco Central do Brasil.',
 PDF:'Formato portátil de documento. O arquivo exportado é uma minuta e deve ser conferido antes do envio.',
 JSON:'Formato de backup dos dados do aplicativo. Guarde o arquivo de exportação em local privado.',
 'Competência':'Mês de referência do pagamento ou registro, que pode ser diferente da data em que o valor saiu da conta.',
 'Consignado':'Empréstimo com desconto em folha. Ele só deixa de consumir a renda quando a suspensão ou substituição estiver formalizada e implementada.',
 'Base referencial':'Valor usado como entrada na simulação, sujeito a documentação e revisão; não equivale necessariamente ao saldo para quitação.',
 'Saldo residual':'Valor que ainda restaria ao final da simulação, caso as condições informadas fossem mantidas. Não é desconto automaticamente concedido.',
 'Parcela global':'Montante mensal que você propõe distribuir entre os credores abrangidos pelo plano.',
 'Rateio':'Forma de repartir a parcela global entre os credores, proporcionalmente às bases ou em partes iguais.',
 'Benefício alimentação':'Valor disponível em vale ou cartão de alimentação. Para não contar a despesa duas vezes, a parcela coberta pelo benefício é descontada do gasto em dinheiro.',
 'Valor bruto':'Custo mensal total da despesa, antes de deduzir qualquer parcela coberta pelo benefício.',
 'Líquido em dinheiro':'Renda efetivamente recebida em conta, já considerado o desconto do consignado quando houver.',
 'Verificado':'Indica que o valor foi conferido em comprovante contratual ou documento bancário atualizado. Importar a planilha não marca valores como verificados.',
 'Saldo cobrado':'Montante informado ou exigido pelo credor; pode divergir da base usada na proposta e do saldo para quitação.',
 'Fonte':'Arquivo, aba e linha de onde o dado foi importado ou referência do documento que o comprova.',
 'Homologação':'Decisão judicial que aprova formalmente o acordo ou plano. A data proposta no sistema não significa aprovação.',
 'Reserva':'Quantia de segurança que deve sobrar depois de cobrir despesas e a parcela proposta, na hipótese simulada.',
 'Encargos':'Taxa mensal de juros ou encargos considerada na simulação. Não constitui automaticamente a taxa contratual ou concedida em acordo.',
 'Conferência':'Revisão de valores, datas, credores, fontes e documentos antes de apresentar uma proposta.',
 'Origem da planilha':'Registro do arquivo, da aba e da linha usados para importar um valor. O arquivo original não é armazenado pelo aplicativo.',
 'Modo demonstração':'Ambiente com números fictícios, sem gravação do caso pessoal no banco.',
});