/** Audit-friendly report data; no automatic legal or accounting conclusion. */
import {evaluate,normalizeCase,brl,REFERENCE} from './engine.mjs';
import {allDossiers,loanSummary,ledgerSummary,EVIDENCE_SOURCES,normalizeEvidence} from './evidence.mjs';
const isoDate=()=>new Date().toISOString().slice(0,10);
const m=x=>x==null?'Pendente':brl(x);
const word=x=>String(x??'').replace(/[\u0000-\u001f]/g,' ').slice(0,1500);
export function makeReport(input,asOf=isoDate()){
 const model=normalizeCase(input),calc=evaluate(model),evidence=normalizeEvidence(model.evidence),dossiers=allDossiers(model,calc);
 const conditional=calc.finance.afterProposal,real=calc.finance.currentGap,loan=loanSummary(model);
 const payments=calc.allocations.reduce((a,x)=>a+x.paid,0);
 const sections=[
 {title:'1. Escopo e ressalvas',body:[`Data da emissão: ${asOf}. Trata-se de minuta técnica com dados de competência distinta; não é laudo pericial nem plano homologado. Valores atuais devem ser confirmados pelos credores.`,`Primeiro vencimento solicitado: ${calc.requestedStart}. Prazo proposto: ${model.plan.months} meses. A distribuição e os saldos são cenários de negociação. Desconto na folha NÃO é considerado suspenso sem comprovação.`]},
 {title:'2. Capacidade familiar',body:[`Renda em dinheiro após consignado: ${brl(calc.finance.cashReceived)}. Despesas que exigem dinheiro: ${brl(calc.finance.cashBudget)}. Resultado atual antes de outras dívidas: ${brl(real)}.`,`Se a substituição do desconto do consignado for efetivamente operacionalizada, disponibilidade de referência: ${brl(calc.finance.conditionalAvailable)}. Parcela global pretendida: ${brl(model.plan.monthly)}. Sobra condicional após as despesas e a parcela: ${brl(conditional)}. Reserva desejada: ${brl(model.plan.reserve)}.`,`Não confundir benefício alimentação com salário em dinheiro. Dízimo e outras rubricas declaradas precisam de avaliação jurídica específica quanto a sua consideração no mínimo existencial.`]},
 {title:'3. Valor e viabilidade do plano',body:[`Soma das bases referenciais incluídas no motor: ${brl(calc.baseTotal)}. Pagamentos projetados no prazo: ${brl(calc.totalPaid)}. Saldo residual ilustrativo: ${brl(calc.totalEnding)}.`,`A parcela ofertada é uma capacidade econômica proposta, não o principal comprovado de cada contrato. ${calc.totalEnding>0?'A soma dos saldos não se liquida integralmente nesta simulação: requer acordo negocial, revisão documental ou reformulação antes de apresentar como plano judicial compulsório.':'Mesmo sem saldo residual modelado, confirmar encargos, classificação de dívidas e atualização.'}`]},
 {title:'4. Itaú consignado',body:[`Total de parcelas nominais futuras cadastradas: ${brl(loan.futureNominal)}. Referência de liquidação: ${m(loan.snapshot)} em ${loan.asOf||'data pendente'}. Não é cotação de quitação atual.`,`Juros registrados nas prestações pagas: ${m(loan.paidInterest)}. Principal amortizado: ${m(loan.paidPrincipal)}. Juros pagos são histórico da composição da dívida, não crédito automático.`,`Valor destinado no plano: ${m(calc.allocations.find(x=>x.id==='itau_cons')?.monthly)}/mês. O desconto atual em folha é ${brl(model.consignado.installment)} e só deixa de ocorrer mediante ato formal e implementação.`]},
 {title:'5. Pendências de documentação',body:[...calc.warnings.map(x=>x.text),...calc.missingData.map(x=>`${x.creditor}: informar ${x.field}.`)]},
 {title:'6. Referências normativas e técnicas',body:[...Object.entries(EVIDENCE_SOURCES).map(([key,url])=>`${key}: ${url}`),...Object.entries(REFERENCE).map(([key,url])=>`${key}: ${url}`)]}
 ];
 return {asOf,model,calc,evidence,dossiers,sections,payments};
}
export function workbookSheets(input){const r=makeReport(input),{model,calc,evidence,dossiers}=r;
 const overview=[['PLANO JUSTO | MEMÓRIA DE CÁLCULO'],['Emitido em',r.asOf],['Nome',model.profile.name],['Processo',model.profile.case],['Primeiro mês solicitado',calc.requestedStart],['Prazo meses',model.plan.months],['Parcela global proposta',model.plan.monthly],['Receita efetiva em dinheiro',calc.finance.cashReceived],['Despesa que exige dinheiro',calc.finance.cashBudget],['Resultado atual',calc.finance.currentGap],['Resultado condicional após substituição e parcela',calc.finance.afterProposal],['Saldo residual ilustrativo',calc.totalEnding],['Homologação',model.plan.signed?'Informada pelo usuário - conferir decisão':'Não informada'],['Fonte','Memória do caso e documentos a conferir']];
 const creditors=[['Identificador','Credor','Incluído?','Cobrado','Base do plano','Parcela mensal','Pago projetado','Saldo residual','Verificado','Fonte'],...dossiers.map(d=>{const c=model.debts.find(x=>x.id===d.id);return [d.id,d.name,c?.mode||'inclusão/coordenação proposta',c?.claim??null,d.allocation?.base??c?.base??null,d.allocation?.monthly??0,d.allocation?.paid??0,d.allocation?.ending??0,c?.verified?'sim':'não',d.source]})];
 const loan=Object.entries({...evidence.loan,...loanSummary(model)}).filter(([k])=>!['contractNote','settlementSource','amortizationSource','negotiationNote'].includes(k)).map(([k,v])=>[k,v]);loan.unshift(['Itaú consignado - valores com data-base','Valor']);loan.push(['Fonte da quitação',evidence.loan.settlementSource],['Fonte da amortização',evidence.loan.amortizationSource],['Notas do contrato',evidence.loan.contractNote]);
 const entries=[['Credor','Data','Categoria','Valor','Descrição','Status documental','Fonte','Operação/rotativo'],...Object.entries(evidence.ledgers).flatMap(([id,rows])=>rows.map(x=>[model.debts.find(d=>d.id===id)?.creditor||id,x.date,x.kind,x.amount,x.description,x.status,x.source,x.operationId]))];
 const reconciliations=[['Credor','Mês','Saldo anterior','Novos lançamentos/encargos','Pagamentos apropriados no período','Fatura esperada','Fatura registrada','Diferença','Há ajuste não discriminado?'],...dossiers.filter(d=>!d.loan).flatMap(d=>(d.summary.cycles||[]).map(c=>[d.name,c.month,c.opening,c.charged,c.paid,c.expected,c.statement,c.difference,c.hasUnexplained?'sim':'não']))];
 const totals=[['Credor','Compras','Juros informados','IOF','Mora','Multa','Tarifas','Parcelas mistas','Ajustes sem discriminação','Pagamentos apropriados','Transferências pendentes'],...dossiers.filter(d=>!d.loan).map(d=>{const t=d.summary.totals;return [d.name,t.purchase,t.interest,t.iof,t.late_interest,t.fine,t.fee,t.financed_installment,t.other_adjustment,t.payment,t.transfer_pending]})];
 const reasons=[['Credor','Seção','Justificativa / pedido'],...dossiers.flatMap(d=>[...d.lines.map(x=>[d.name,x.title,x.text]),...d.requests.map(x=>[d.name,'Documento solicitado',x]),...d.warnings.map(x=>[d.name,'Ressalva',x])])];
 const timeline=[['Credor','Data','Providência','Resultado','Status','Prova/fonte'],...evidence.actions.map(x=>[x.creditorId,x.date,x.action,x.outcome,x.status,x.source])];
 const pay=[['Despesa','Categoria','Valor bruto','Benefício aplicado','Gasto em dinheiro informado','Fonte'],...model.budget.map(x=>[x.name,x.category,x.gross,x.ticket,Math.max(0,x.gross-x.ticket),x.source])];
 const schedule=[['Mês','Número','Credor','Saldo inicial','Juros simulados','Pagamento','Saldo final'],...calc.schedule.map(x=>[x.month,x.index,x.creditor,x.opening,x.interest,x.payment,x.ending])];
 const pending=[['Credor','Campo exigido não informado'],...calc.missingData.map(x=>[x.creditor,x.field])];
 const sources=[['Referência','URL'],...Object.entries(EVIDENCE_SOURCES).map(([k,url])=>[k,url])];
 return {Resumo:overview,Credores:creditors,Consignado:loan,Lancamentos:entries,Conciliação:reconciliations,Encargos:totals,Justificativas:reasons,Providencias:timeline,Orcamento:pay,Cronograma:schedule,Pendencias:pending,Referencias:sources};
}
export function creditorText(input,report,id){const dossier=allDossiers(input,report).find(x=>x.id===id);if(!dossier)throw Error('Credor inválido');return [`DOSSIE | ${dossier.name}`,`Documento de trabalho; conferir com contratos e faturas originais.`,...dossier.lines.flatMap(x=>[x.title,x.text]),'PEDIDOS DE DOCUMENTOS',...dossier.requests,'RESSALVAS',...dossier.warnings].join('\n\n')}
export function exportFileName(suffix,format){return `Plano_Justo_${suffix}_${isoDate()}.${format}`}