import React,{useMemo,useRef,useState} from 'react';
import {BANK_REQUESTS,KNOWLEDGE_TYPES,KNOWLEDGE_STATUSES,LEGAL_LIBRARY,REQUIRED_CREDITOR_FIELDS,knowledgeCoverage,normalizeKnowledge,mergeKnowledge} from '../../shared/knowledge.mjs';
const newItem=()=>({id:typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`e-${Date.now()}`,date:'',type:'procedural_event',title:'',actor:'',creditorId:'',summary:'',sourceId:'',sourcePage:'',sourceUrl:'',status:'pending'});
const TAGS={court_order:'Decisão',procedural_event:'Andamento',party_statement:'Manifestação',bank_response:'Resposta do banco',financial_evidence:'Documento financeiro',court_precedent:'Precedente',professional_note:'Nota jurídica',user_statement:'Declaração'};
export default function CaseKnowledgePanel({model,onChange}){
 const [draft,setDraft]=useState(newItem),[status,setStatus]=useState(''),[filter,setFilter]=useState('all');const ref=useRef();const k=normalizeKnowledge(model.knowledge),coverage=useMemo(()=>knowledgeCoverage(k),[model.knowledge]);
 const options=[{id:'',name:'Geral / processo'},{id:'itau_cons',name:'Itaú consignado'},...model.debts.map(d=>({id:d.id,name:d.creditor}))];
 function add(e){e.preventDefault();if(!draft.title.trim()||!draft.summary.trim()||!draft.sourceId.trim()){setStatus('Preencha título, conteúdo e referência do documento antes de registrar.');return;}onChange(normalizeKnowledge({items:[...k.items,{...draft}]}));setDraft(newItem());setStatus('Referência adicionada à tela; clique em Salvar alterações para gravar no banco privado.');}
 function remove(id){if(!window.confirm('Retirar esta referência do caso? A alteração só será persistida quando você salvar.'))return;onChange(normalizeKnowledge({items:k.items.filter(x=>x.id!==id)}));}
 async function importFile(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>200000)throw Error('Arquivo acima de 200 KB. Use um complemento estruturado com resumos, sem PDFs ou anexos integrais.');const data=JSON.parse(await file.text());if(!data||(!Array.isArray(data.items)&&!Array.isArray(data.knowledge?.items)))throw Error('É necessário JSON com items ou knowledge.items.');const incoming=data.knowledge||data;const parsed=normalizeKnowledge(incoming);if(!parsed.items.length)throw Error('Nenhuma referência completa com título, conteúdo e documento.');if(!window.confirm(`Mesclar ${parsed.items.length} referências com o seu caso? Os registros existentes serão preservados; nada será publicado no GitHub.`))return;const merged=mergeKnowledge(k,parsed);onChange(merged);setStatus(`${merged.items.length-k.items.length} nova(s) referência(s) incluída(s), sem sobrescrever as atuais. Clique em Salvar alterações.`);}catch(err){setStatus(err.message)}e.target.value='';}
 const entries=k.items.filter(x=>filter==='all'||x.type===filter).sort((a,b)=>b.date.localeCompare(a.date));
 return <section className="panel" id="case-knowledge"><div className="section-head"><div><h3>▤ Memória jurídica do seu processo</h3><p>Decisões, movimentos, representantes e respostas bancárias, com data e referência. A IA usa estes registros junto aos seus cálculos. Documentos integrais permanecem com você.</p></div></div>
  <div className="knowledge-stats"><div><b>{coverage.total}</b><span>registros com fonte</span></div><div><b>{coverage.orders}</b><span>decisões identificadas</span></div><div><b>{coverage.bankResponses}</b><span>respostas documentadas</span></div><div><b>{coverage.unverified}</b><span>itens a conferir</span></div></div>
  {coverage.missingHearing&&<div className="alert amber"><b>Audiência ainda não comprovada neste cadastro</b><p>O despacho que manda designar audiência não informa, por si só, data ou confirmação de realização. Atualize com a intimação ou a ata quando estiver disponível.</p></div>}
  <div className="alert blue"><b>O que a IA sabe sobre o juiz e os advogados?</b><p>Somente nomes, cargos, atos assinados e manifestações que apareçam nos documentos. Ela não deduz intenções, preferências pessoais, resultado provável ou estratégia interna de quem não se manifestou nos autos.</p></div>
  <div className="knowledge-actions"><button className="ghost" onClick={()=>ref.current?.click()}>⇧ Importar complemento do processo (JSON)</button><input type="file" accept=".json,application/json" ref={ref} hidden onChange={importFile}/><a target="_blank" rel="noreferrer" href="https://pje-consultapublica.tjdft.jus.br/consultapublica/ConsultaPublica/listView.seam">Conferir andamento no PJe ↗</a></div>
  {status&&<div className="alert blue" role="status">{status}</div>}
  <details className="knowledge-details"><summary>Exigências específicas da decisão: sete campos por contrato</summary><div className="knowledge-checklist">{REQUIRED_CREDITOR_FIELDS.map((x,i)=><div key={x.id}><b>{i+1}.</b> {x.label}</div>)}</div><small>Além dos campos, o DDC e as faturas precisam permitir reconciliação de principal, juros, encargos e pagamentos. A data-base deve aparecer em cada saldo.</small></details>
  <form onSubmit={add} className="knowledge-form"><h4>Adicionar decisão, manifestação ou documento</h4><div className="formgrid"><label>Tipo<select value={draft.type} onChange={e=>setDraft(x=>({...x,type:e.target.value}))}>{Object.entries(KNOWLEDGE_TYPES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Data do ato<input type="date" value={draft.date} onChange={e=>setDraft(x=>({...x,date:e.target.value}))}/></label><label>Escopo / instituição<select value={draft.creditorId} onChange={e=>setDraft(x=>({...x,creditorId:e.target.value}))}>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Responsável identificado no documento<input value={draft.actor} maxLength={140} placeholder="Ex.: magistrado que assinou; representante; não presumir" onChange={e=>setDraft(x=>({...x,actor:e.target.value}))}/></label><label>Título<input required maxLength={170} value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))} placeholder="Ex.: Decisão – requerimento de demonstrativos"/></label><label>Conferência<select value={draft.status} onChange={e=>setDraft(x=>({...x,status:e.target.value}))}>{Object.entries(KNOWLEDGE_STATUSES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Identificação da fonte<input required maxLength={160} value={draft.sourceId} onChange={e=>setDraft(x=>({...x,sourceId:e.target.value}))} placeholder="Ex.: PJe ID 288960242 / DDC Itaú 04-08-2026"/></label><label>Página / seção<input maxLength={35} value={draft.sourcePage} onChange={e=>setDraft(x=>({...x,sourcePage:e.target.value}))} placeholder="Pág. 5"/></label></div><label>Resumo fiel, com alegações atribuídas<textarea required maxLength={1350} rows={4} value={draft.summary} onChange={e=>setDraft(x=>({...x,summary:e.target.value}))} placeholder="O que o documento realmente registra; diferencie decisão, pedido de parte e alegação do banco."/></label><button className="primary" type="submit">+ Registrar referência no caso</button></form>
  <h4>Histórico identificado</h4><label className="knowledge-filter">Filtrar por tipo<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option>{Object.entries(KNOWLEDGE_TYPES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
  <div className="knowledge-timeline">{entries.length?entries.map(item=><article className="knowledge-entry" key={item.id}><div><b>{item.date||'Data pendente'} · {TAGS[item.type]}</b><button type="button" className="ghost" onClick={()=>remove(item.id)} aria-label={`Retirar referência ${item.title}`}>×</button></div><strong>{item.title}</strong><p>{item.summary}</p><small><b>Fonte:</b> {item.sourceId}{item.sourcePage?`, ${item.sourcePage}`:''} · {KNOWLEDGE_STATUSES[item.status]}{item.actor?` · ${item.actor}`:''}</small></article>):<div className="alert amber">Sem referências privadas. Importe o complemento de processo ou registre os documentos com fonte.</div>}</div>
  <details className="knowledge-details"><summary>Biblioteca de legislação e procedimento (fontes oficiais)</summary><p className="muted">Links de consulta, não textos incorporados integralmente ou precedentes aplicados automaticamente ao caso. O servidor sinaliza quais páginas conseguiu ler.</p><div className="knowledge-laws">{LEGAL_LIBRARY.map(x=><article key={x.id}><b>{x.id} · {x.topic}</b><a target="_blank" rel="noreferrer" href={x.url}>{x.name} ↗</a><small>{x.note}</small></article>)}</div></details>
  <details className="knowledge-details"><summary>Documentos que cada instituição deve esclarecer</summary>{Object.entries(BANK_REQUESTS).map(([id,list])=><div key={id}><h4>{options.find(x=>x.id===id)?.name||id}</h4><div className="knowledge-checklist">{list.map((x,i)=><div key={i}>□ {x}</div>)}</div></div>)}</details>
 </section>;
}