import React,{useMemo,useRef,useState} from 'react';
import {ACTOR_ROLES,ACTOR_STATUSES,participantAudit,normalizeParticipants} from '../../shared/actor-audit.mjs';
import {BANK_REQUESTS,KNOWLEDGE_TYPES,KNOWLEDGE_STATUSES,LEGAL_LIBRARY,REQUIRED_CREDITOR_FIELDS,knowledgeCoverage,normalizeKnowledge,mergeKnowledge} from '../../shared/knowledge.mjs';
const newItem=()=>({id:typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`e-${Date.now()}`,date:'',type:'procedural_event',title:'',actor:'',creditorId:'',summary:'',sourceId:'',sourcePage:'',sourceUrl:'',status:'pending'});
const actorDraft=()=>({id:typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`actor-${Date.now()}`,name:'',role:'lawyer',representedParty:'',professionalRegistration:'',sourceId:'',sourcePage:'',sourceUrl:'',sourceDate:'',status:'pending',scope:'',documentaryNote:''});
const TAGS={court_order:'Decisão',procedural_event:'Andamento',party_statement:'Manifestação',bank_response:'Resposta do banco',financial_evidence:'Documento financeiro',court_precedent:'Precedente',professional_note:'Nota jurídica',user_statement:'Declaração'};
export default function CaseKnowledgePanel({model,onChange}){
 const [draft,setDraft]=useState(newItem),[person,setPerson]=useState(actorDraft),[status,setStatus]=useState(''),[filter,setFilter]=useState('all');const ref=useRef();const k=normalizeKnowledge(model.knowledge),coverage=useMemo(()=>knowledgeCoverage(k),[model.knowledge]);
 const actors=useMemo(()=>participantAudit(k),[model.knowledge]);const options=[{id:'',name:'Geral / processo'},{id:'itau_cons',name:'Itaú consignado'},...model.debts.map(d=>({id:d.id,name:d.creditor}))];
 function add(e){e.preventDefault();if(!draft.title.trim()||!draft.summary.trim()||!draft.sourceId.trim()){setStatus('Preencha título, conteúdo e referência do documento antes de registrar.');return;}onChange(normalizeKnowledge({...k,items:[...k.items,{...draft}]}));setDraft(newItem());setStatus('Referência adicionada à tela; clique em Salvar alterações para gravar no banco privado.');}
 function remove(id){if(!window.confirm('Retirar esta referência do caso? A alteração só será persistida quando você salvar.'))return;onChange(normalizeKnowledge({...k,items:k.items.filter(x=>x.id!==id)}));}
 async function importFile(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>200000)throw Error('Arquivo acima de 200 KB. Use um complemento estruturado com resumos, sem PDFs ou anexos integrais.');const data=JSON.parse(await file.text());if(!data||(!Array.isArray(data.items)&&!Array.isArray(data.knowledge?.items)&&!Array.isArray(data.participants)&&!Array.isArray(data.knowledge?.participants)))throw Error('É necessário JSON com items/participants ou knowledge.items/participants.');const incoming=data.knowledge||data;const parsed=normalizeKnowledge(incoming);if(!parsed.items.length&&!parsed.participants.length)throw Error('Nenhuma referência ou representante com identificação de fonte.');if(!window.confirm(`Mesclar ${parsed.items.length} referências e ${parsed.participants.length} participantes com o seu caso? Os registros existentes serão preservados; nada será publicado no GitHub.`))return;const merged=mergeKnowledge(k,parsed);onChange(merged);setStatus(`${merged.items.length-k.items.length} referência(s) e ${merged.participants.length-k.participants.length} participante(s) incluído(s), sem sobrescrever os atuais. Clique em Salvar alterações.`);}catch(err){setStatus(err.message)}e.target.value='';}

 function addPerson(e){e.preventDefault();if(!person.name.trim()||!person.sourceId.trim()){setStatus('O nome e a fonte do cadastro são obrigatórios.');return;}onChange(normalizeKnowledge({...k,participants:[...k.participants,person]}));setPerson(actorDraft());setStatus('Participante adicionado à memória privada. Confirme a vinculação pelo PJe e clique em Salvar alterações.');}
 function removePerson(id){if(!window.confirm('Retirar este participante do cadastro? Salve para persistir.'))return;onChange(normalizeKnowledge({...k,participants:k.participants.filter(p=>p.id!==id)}));}
 const entries=k.items.filter(x=>filter==='all'||x.type===filter).sort((a,b)=>b.date.localeCompare(a.date));
 return <section className="panel" id="case-knowledge"><div className="section-head"><div><h3>▤ Memória jurídica do seu processo</h3><p>Decisões, movimentos, representantes e respostas bancárias, com data e referência. A IA usa estes registros junto aos seus cálculos. Documentos integrais permanecem com você.</p></div></div>
  <div className="knowledge-stats"><div><b>{coverage.total}</b><span>registros com fonte</span></div><div><b>{coverage.orders}</b><span>decisões identificadas</span></div><div><b>{coverage.bankResponses}</b><span>respostas documentadas</span></div><div><b>{coverage.unverified}</b><span>itens a conferir</span></div></div>
  {coverage.missingHearing&&<div className="alert amber"><b>Audiência ainda não comprovada neste cadastro</b><p>O despacho que manda designar audiência não informa, por si só, data ou confirmação de realização. Atualize com a intimação ou a ata quando estiver disponível.</p></div>}
  <div className="alert blue"><b>O que a IA sabe sobre o juiz e os advogados?</b><p>Somente nomes, cargos, atos assinados e manifestações que apareçam nos documentos. Ela não deduz intenções, preferências pessoais, resultado provável ou estratégia interna de quem não se manifestou nos autos.</p></div>
  <div className="knowledge-actions"><button className="ghost" onClick={()=>ref.current?.click()}>⇧ Importar complemento do processo (JSON)</button><input type="file" accept=".json,application/json" ref={ref} hidden onChange={importFile}/><a target="_blank" rel="noreferrer" href="https://pje-consultapublica.tjdft.jus.br/consultapublica/ConsultaPublica/listView.seam">Conferir andamento no PJe ↗</a></div>
  {status&&<div className="alert blue" role="status">{status}</div>}
  <details className="knowledge-details actor-knowledge" open><summary>Representantes, bancos e atuação documentada</summary>
   <p className="muted">A IA consulta este cadastro privado. A vinculação exibida numa captura precisa de conferência na capa atualizada e na procuração; nome ou OAB não provam uma tese jurídica nem uma manifestação individual.</p>
   <div className="knowledge-stats"><div><b>{actors.total}</b><span>participantes cadastrados</span></div><div><b>{actors.lawyers}</b><span>advogados identificados</span></div><div><b>{actors.pending}</b><span>vínculos a conferir</span></div><div><b>{actors.documentedActionSources}</b><span>fontes processuais indexadas</span></div></div>
   {actors.gaps.slice(0,5).map((v,i)=><div className="alert amber" key={i}>{v}</div>)}
   <div className="actor-list">{k.participants.map(a=><article key={a.id} className="knowledge-entry"><div><b>{ACTOR_ROLES[a.role]} · {ACTOR_STATUSES[a.status]}</b><button type="button" className="ghost" aria-label={`Retirar ${a.name}`} onClick={()=>removePerson(a.id)}>×</button></div><strong>{a.name}</strong><p>{a.representedParty?`Vinculação indicada: ${a.representedParty}`:'Vinculação não indicada'}{a.professionalRegistration?` · ${a.professionalRegistration}`:''}</p><small>Fonte: {a.sourceId}{a.sourcePage?`, ${a.sourcePage}`:''}{a.sourceDate?` · capturado em ${a.sourceDate}`:''}</small>{a.documentaryNote&&<p className="muted">{a.documentaryNote}</p>}</article>)}</div>
   <form onSubmit={addPerson} className="knowledge-form"><h4>Registrar representante ou parte</h4><div className="formgrid">
    <label>Nome / razão social<input required maxLength={160} value={person.name} onChange={e=>setPerson(p=>({...p,name:e.target.value}))}/></label>
    <label>Tipo<select value={person.role} onChange={e=>setPerson(p=>({...p,role:e.target.value}))}>{Object.entries(ACTOR_ROLES).map(([key,val])=><option key={key} value={key}>{val}</option>)}</select></label>
    <label>Parte que representa (somente se documentada)<input value={person.representedParty} maxLength={170} onChange={e=>setPerson(p=>({...p,representedParty:e.target.value}))} placeholder="Ex.: Banco... ou a confirmar"/></label>
    <label>OAB / registro profissional<input maxLength={55} value={person.professionalRegistration} onChange={e=>setPerson(p=>({...p,professionalRegistration:e.target.value}))} placeholder="Sem CPF"/></label>
    <label>Identificação do documento<input required maxLength={160} value={person.sourceId} onChange={e=>setPerson(p=>({...p,sourceId:e.target.value}))}/></label>
    <label>Status da vinculação<select value={person.status} onChange={e=>setPerson(p=>({...p,status:e.target.value}))}>{Object.entries(ACTOR_STATUSES).map(([key,val])=><option key={key} value={key}>{val}</option>)}</select></label>
    <label>Data do documento<input type="date" value={person.sourceDate} onChange={e=>setPerson(p=>({...p,sourceDate:e.target.value}))}/></label>
    <label>Página / seção<input value={person.sourcePage} maxLength={35} onChange={e=>setPerson(p=>({...p,sourcePage:e.target.value}))}/></label></div>
    <label>Observação sobre atuação efetivamente comprovada<textarea rows={2} maxLength={450} value={person.documentaryNote} onChange={e=>setPerson(p=>({...p,documentaryNote:e.target.value}))}/></label>
    <button className="primary" type="submit">+ Registrar participante</button></form>
  </details>
  <details className="knowledge-details"><summary>Exigências específicas da decisão: sete campos por contrato</summary><div className="knowledge-checklist">{REQUIRED_CREDITOR_FIELDS.map((x,i)=><div key={x.id}><b>{i+1}.</b> {x.label}</div>)}</div><small>Além dos campos, o DDC e as faturas precisam permitir reconciliação de principal, juros, encargos e pagamentos. A data-base deve aparecer em cada saldo.</small></details>
  <form onSubmit={add} className="knowledge-form"><h4>Adicionar decisão, manifestação ou documento</h4><div className="formgrid"><label>Tipo<select value={draft.type} onChange={e=>setDraft(x=>({...x,type:e.target.value}))}>{Object.entries(KNOWLEDGE_TYPES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Data do ato<input type="date" value={draft.date} onChange={e=>setDraft(x=>({...x,date:e.target.value}))}/></label><label>Escopo / instituição<select value={draft.creditorId} onChange={e=>setDraft(x=>({...x,creditorId:e.target.value}))}>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Responsável identificado no documento<input value={draft.actor} maxLength={140} placeholder="Ex.: magistrado que assinou; representante; não presumir" onChange={e=>setDraft(x=>({...x,actor:e.target.value}))}/></label><label>Título<input required maxLength={170} value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))} placeholder="Ex.: Decisão – requerimento de demonstrativos"/></label><label>Conferência<select value={draft.status} onChange={e=>setDraft(x=>({...x,status:e.target.value}))}>{Object.entries(KNOWLEDGE_STATUSES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Identificação da fonte<input required maxLength={160} value={draft.sourceId} onChange={e=>setDraft(x=>({...x,sourceId:e.target.value}))} placeholder="Ex.: PJe ID 288960242 / DDC Itaú 04-08-2026"/></label><label>Página / seção<input maxLength={35} value={draft.sourcePage} onChange={e=>setDraft(x=>({...x,sourcePage:e.target.value}))} placeholder="Pág. 5"/></label></div><label>Resumo fiel, com alegações atribuídas<textarea required maxLength={1350} rows={4} value={draft.summary} onChange={e=>setDraft(x=>({...x,summary:e.target.value}))} placeholder="O que o documento realmente registra; diferencie decisão, pedido de parte e alegação do banco."/></label><button className="primary" type="submit">+ Registrar referência no caso</button></form>
  <h4>Histórico identificado</h4><label className="knowledge-filter">Filtrar por tipo<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option>{Object.entries(KNOWLEDGE_TYPES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
  <div className="knowledge-timeline">{entries.length?entries.map(item=><article className="knowledge-entry" key={item.id}><div><b>{item.date||'Data pendente'} · {TAGS[item.type]}</b><button type="button" className="ghost" onClick={()=>remove(item.id)} aria-label={`Retirar referência ${item.title}`}>×</button></div><strong>{item.title}</strong><p>{item.summary}</p><small><b>Fonte:</b> {item.sourceId}{item.sourcePage?`, ${item.sourcePage}`:''} · {KNOWLEDGE_STATUSES[item.status]}{item.actor?` · ${item.actor}`:''}</small></article>):<div className="alert amber">Sem referências privadas. Importe o complemento de processo ou registre os documentos com fonte.</div>}</div>
  <details className="knowledge-details"><summary>Biblioteca de legislação e procedimento (fontes oficiais)</summary><p className="muted">Links de consulta, não textos incorporados integralmente ou precedentes aplicados automaticamente ao caso. O servidor sinaliza quais páginas conseguiu ler.</p><div className="knowledge-laws">{LEGAL_LIBRARY.map(x=><article key={x.id}><b>{x.id} · {x.topic}</b><a target="_blank" rel="noreferrer" href={x.url}>{x.name} ↗</a><small>{x.note}</small></article>)}</div></details>
  <details className="knowledge-details"><summary>Documentos que cada instituição deve esclarecer</summary>{Object.entries(BANK_REQUESTS).map(([id,list])=><div key={id}><h4>{options.find(x=>x.id===id)?.name||id}</h4><div className="knowledge-checklist">{list.map((x,i)=><div key={i}>□ {x}</div>)}</div></div>)}</details>
 </section>;
}