import React,{useMemo,useState} from 'react';
import {brl,evaluate,normalizeCase} from '../../shared/engine.mjs';
import {LEDGER_TYPES,normalizeEvidence,creditorDossier,EVIDENCE_SOURCES} from '../../shared/evidence.mjs';
import {downloadGeneralPdf,downloadCreditorPdf,downloadRequestsPdf,downloadWorkbook} from './reports.js';
import {Help} from './Help.jsx';
import CaseKnowledgePanel from './CaseKnowledgePanel.jsx';
import DossierIntelligence from './DossierIntelligence.jsx';
const NUMERIC={originalFinanced:'Total financiado',cashReleased:'Crédito líquido recebido em conta',priorSettled:'Contratos anteriores refinanciados',financedTax:'IOF financiado',nominalOriginal:'Soma nominal original',rateMonthly:'Taxa mensal (%)',cetMonthly:'CET mensal (%)',paidPrincipal:'Principal já amortizado',paidInterest:'Juros já pagos',paidOther:'Outros encargos pagos',paidTotal:'Total de pagamentos registrados',firstInterest:'Juros na primeira parcela',settlementAmount:'Cotação de quitação na data-base',negotiationReference:'Referência de proposta, ainda não principal'};
const STATUSES={bank_document:'Fatura/DDC bancário conferido',memorial:'Transcrito do memorial - verificar original',declaration:'Declaração/estimativa',unreconciled:'Pendente de conciliação'};
const field=(value,onChange,type='text',props={})=><input type={type} value={value??''} onChange={e=>onChange(type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} {...props}/>;
export default function DossierPanel({model,onChange,onKnowledgeChange,onError,record,session,db,dirty,demoMode}){
 const [selected,setSelected]=useState('itau_cons'),[exporting,setExporting]=useState(false),[note,setNote]=useState('');
 const r=useMemo(()=>evaluate(model),[model]),e=normalizeEvidence(model.evidence),d=creditorDossier(model,r,selected);
 const banks=[{id:'itau_cons',creditor:'Itaú - consignado'},...model.debts.map(x=>({id:x.id,creditor:x.creditor}))];
 function commit(evidence){onChange(normalizeEvidence(evidence));}
 function changeLoan(k,val){commit({...e,loan:{...e.loan,[k]:val}})}
 function changeLedger(i,k,val){const rows=[...(e.ledgers[selected]||[])];rows[i]={...rows[i],[k]:val};commit({...e,ledgers:{...e.ledgers,[selected]:rows}})}
 function addLedger(){const rows=e.ledgers[selected]||[];commit({...e,ledgers:{...e.ledgers,[selected]:[...rows,{id:crypto.randomUUID(),date:'',kind:'purchase',amount:0,description:'',source:'',status:'unreconciled',operationId:''}]}})}
 function removeLedger(i){if(!window.confirm('Excluir esta linha histórica?'))return;commit({...e,ledgers:{...e.ledgers,[selected]:(e.ledgers[selected]||[]).filter((_,index)=>i!==index)}})}
 function addAction(){commit({...e,actions:[...e.actions,{id:crypto.randomUUID(),date:'',creditorId:selected,action:'',source:'',outcome:'',status:'pendente'}]})}
 function changeAction(i,k,value){const actions=[...e.actions];actions[i]={...actions[i],[k]:value};commit({...e,actions})}
 function removeAction(id){if(!window.confirm('Excluir a providência do histórico?'))return;commit({...e,actions:e.actions.filter(x=>x.id!==id)})}
 async function run(action){setExporting(true);setNote('');try{await action();setNote('Documento preparado para baixar. Confira os valores e anexos originais antes de utilizar.')}catch(err){onError?.(err.message||'Não foi possível gerar o arquivo.');}finally{setExporting(false)}}
 return <>
  <section className="panel" id="exports"><div className="section-head"><div><h3>Central de documentos para o advogado</h3><p>Exporte os cálculos e os argumentos individualizados. Documentos de trabalho, não homologação ou perícia.</p></div></div>
   <div className="export-grid"><button className="primary" disabled={exporting} onClick={()=>run(()=>downloadGeneralPdf(model))}>↓ PDF completo e justificativas</button><button className="ghost" disabled={exporting} onClick={()=>run(()=>downloadWorkbook(model))}>↓ Excel - conciliação e 60 meses</button><button className="ghost" disabled={exporting} onClick={()=>run(()=>downloadRequestsPdf(model))}>↓ PDF - pedidos de documentos</button><button className="ghost" disabled={exporting} onClick={()=>run(()=>downloadCreditorPdf(model,selected))}>↓ PDF do credor selecionado</button></div>
   {note&&<div role="status" className="alert green">{note}</div>}
   <div className="alert amber">O PDF traz uma fundamentação factual e pedidos a verificar, mas não afirma que a diferença entre parcelas nominais e saldo de quitação seja dívida indevida. Juros pagos não são descontados novamente sem base contratual ou decisão.</div>
  </section>
  <CaseKnowledgePanel model={model} onChange={onKnowledgeChange}/>
  <DossierIntelligence model={model} record={record} session={session} db={db} dirty={dirty} demoMode={demoMode}/>
  <section className="panel"><div className="section-head"><div><h3>1. Escolha o credor e revise sua justificativa <Help term="Base referencial"/></h3><p>Use a justificativa por instituição e confira os valores antes de exportar.</p></div></div>
    <label className="dossier-choice">Credor<select value={selected} onChange={ev=>setSelected(ev.target.value)}>{banks.map(x=><option key={x.id} value={x.id}>{x.creditor}</option>)}</select></label>
    <div className="dossier-facts">{d.lines.map((x,i)=><div key={i} className="dossier-item"><b>{x.title}</b><p>{x.text}</p></div>)}</div>
    <div className="alert blue"><b>Exibição documental solicitada</b>{d.requests.map((x,i)=><p key={i}>• {x}</p>)}</div>{d.warnings.map((x,i)=><div key={i} className="alert amber">{x}</div>)}
  </section>
  {selected==='itau_cons'?<section className="panel"><div className="section-head"><div><h3>2. Itaú - histórico de principal, juros e saldo</h3><p>Atualize os valores apenas a partir do contrato/DDC. A data-base acompanha a cotação de quitação.</p></div></div>
    <label className="dossier-choice">Número do contrato{field(e.loan.contractNumber,val=>changeLoan('contractNumber',val))}</label><div className="formgrid">{Object.entries(NUMERIC).map(([key,title])=><label key={key}>{title}{field(e.loan[key],value=>changeLoan(key,value),'number',{placeholder:'Pendente'})}</label>)}<label>Data-base da cotação{field(e.loan.settlementAsOf,val=>changeLoan('settlementAsOf',val),'date')}</label><label>Fonte da quitação{field(e.loan.settlementSource,val=>changeLoan('settlementSource',val))}</label><label>Fonte das parcelas/amortização{field(e.loan.amortizationSource,val=>changeLoan('amortizationSource',val))}</label></div>
    <label className="dossier-choice">Observação do contrato<textarea rows="3" value={e.loan.contractNote} onChange={ev=>changeLoan('contractNote',ev.target.value)} placeholder="Indicar fonte e situação do refinanciamento..."/></label>
  </section>:<section className="panel"><div className="section-head"><div><h3>2. Lançamentos e evolução da fatura</h3><p>Separe compras de juros, IOF, multa e diferenças não explicadas. Uma transferência em análise não deve ser abatida como pagamento.</p></div></div>
   <div className="alert blue">Registre a data do ciclo e a fonte. “Diferença não discriminada” não é sinônimo de juros abusivos. O teto de encargos do rotativo é conferido por operação, não pelo saldo agregado do cartão. <a href={EVIDENCE_SOURCES.card} target="_blank" rel="noreferrer">Fonte: Banco Central ↗</a></div>
   <div className="table-wrap"><table className="ledger-table"><thead><tr><th>Data</th><th>Natureza <Help term="Encargos"/></th><th>Valor (R$)</th><th>Descrição</th><th>Fonte</th><th>Status</th><th>Operação</th><th></th></tr></thead><tbody>{(e.ledgers[selected]||[]).map((row,i)=><tr key={row.id}><td>{field(row.date,v=>changeLedger(i,'date',v),'date')}</td><td><select value={row.kind} onChange={ev=>changeLedger(i,'kind',ev.target.value)}>{Object.entries(LEDGER_TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td>{field(row.amount,v=>changeLedger(i,'amount',v),'number')}</td><td>{field(row.description,v=>changeLedger(i,'description',v),'text',{placeholder:'Detalhe'})}</td><td>{field(row.source,v=>changeLedger(i,'source',v),'text',{placeholder:'Documento e página'})}</td><td><select value={row.status} onChange={ev=>changeLedger(i,'status',ev.target.value)}>{Object.entries(STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></td><td>{field(row.operationId,v=>changeLedger(i,'operationId',v),'text',{placeholder:'ID da operação'})}</td><td><button className="ghost" onClick={()=>removeLedger(i)} aria-label="Excluir lançamento">×</button></td></tr>)}</tbody></table></div><button className="ghost" onClick={addLedger}>+ Adicionar lançamento</button>
   {!!d.summary.cycles.length&&<><h4>Conciliação por competência</h4><div className="table-wrap"><table><thead><tr><th>Mês</th><th>Anterior</th><th>Lançamentos + encargos</th><th>Pagamentos</th><th>Esperado</th><th>Fatura</th><th>Diferença</th></tr></thead><tbody>{d.summary.cycles.map(x=><tr key={x.month}><td>{x.month}</td><td>{x.opening==null?'Pendente':brl(x.opening)}</td><td>{brl(x.charged)}</td><td>{brl(x.paid)}</td><td>{x.expected==null?'Pendente':brl(x.expected)}</td><td>{x.statement==null?'Pendente':brl(x.statement)}</td><td>{x.difference==null?'Pendente':brl(x.difference)}</td></tr>)}</tbody></table></div></>}
  </section>}
  <section className="panel"><div className="section-head"><div><h3>3. Providências já tomadas e resultados</h3><p>Registre negociações, protocolos, pedidos de redução, pagamentos e manifestações; explique a fonte e o resultado, sem presumir decisão favorável.</p></div></div>
  {e.actions.map((row,i)=><div className="action-row" key={row.id}><label>Data{field(row.date,v=>changeAction(i,'date',v),'date')}</label><label>Credor<select value={row.creditorId} onChange={ev=>changeAction(i,'creditorId',ev.target.value)}><option value="">Geral</option>{banks.map(b=><option key={b.id} value={b.id}>{b.creditor}</option>)}</select></label><label>Providência{field(row.action,v=>changeAction(i,'action',v))}</label><label>Resultado{field(row.outcome,v=>changeAction(i,'outcome',v))}</label><label>Protocolo/fonte{field(row.source,v=>changeAction(i,'source',v))}</label><label>Situação<select value={row.status} onChange={ev=>changeAction(i,'status',ev.target.value)}>{['pendente','solicitado','realizado','confirmado'].map(s=><option value={s} key={s}>{s}</option>)}</select></label><button className="ghost" onClick={()=>removeAction(row.id)} aria-label="Excluir providência">×</button></div>)}<button className="ghost" onClick={addAction}>+ Registrar providência</button>
  </section>
  <div className="alert blue">Os lançamentos são armazenados no seu caso somente quando você clica em <b>Salvar alterações</b>. Arquivos originais não são anexados automaticamente ao banco nem ao PDF.</div>
 </>;
}