import React,{useMemo,useState} from 'react';
import {strategicFindings,OFFICIAL_RESEARCH_SOURCES} from '../../shared/strategy.mjs';
const STATUS={comprovado:'Fato apontado nos dados – conferir original',a_verificar:'Pendente de prova',proposta:'Possibilidade para discussão'};
async function downloadAnalysis(result){const {jsPDF}=await import('jspdf');const doc=new jsPDF(),margin=16,max=179;let y=18;
 const put=(value,heading=false)=>{const text=String(value??''),lines=doc.splitTextToSize(text,max);const h=heading?6.6:5.4;if(y+lines.length*h>279){doc.addPage();y=17}doc.setFont('helvetica',heading?'bold':'normal');doc.setFontSize(heading?12:9);doc.text(lines,margin,y);y+=Math.max(1,lines.length)*h+2;};
 put('PLANO JUSTO | ANÁLISE DOCUMENTAL ASSISTIDA POR IA',true);put(`Gerada em: ${new Date(result.generatedAt).toLocaleString('pt-BR')} | Versão do caso: ${result.caseVersion}`);put('Documento de trabalho para revisão humana: não é perícia, petição, previsão de aprovação nem decisão judicial.');put('SÍNTESE',true);put(result.report.summary);
 put('PONTOS PARA REVISÃO',true);result.report.priorities.forEach((x,i)=>{put(`${i+1}. ${x.topic} [${STATUS[x.status]||'Conferir'}]`,true);put(x.why);put(`Comprovação: ${x.evidence}`);if(x.sourceIds.length)put(`Fontes oficiais consultadas: ${x.sourceIds.join(', ')}`);if(x.caseSourceIds?.length)put(`Documentos do caso: ${x.caseSourceIds.join(', ')}`)});
 put('ANÁLISE INDIVIDUAL POR CREDOR',true);result.report.creditorStrategy.forEach(x=>{put(x.creditor,true);put(x.factualArgument);put(`Solicitar/verificar: ${x.request}`);put(`Ressalva: ${x.caveat}`);if(x.caseSourceIds?.length)put(`Documentos do caso: ${x.caseSourceIds.join(', ')}`)});
 put('LEITURA DOCUMENTAL DOS ATOS DO PROCESSO',true);(result.report.proceduralReading||[]).forEach(x=>{put(x.documentedAct,true);put(x.implication);put(`Documentos do caso: ${(x.caseSourceIds||[]).join(', ')||'não indicado'}`)});put('PERGUNTAS PARA ADVOGADO',true);result.report.lawyerQuestions.forEach((x,i)=>put(`${i+1}. ${x}`));put('RESSALVAS',true);result.report.cautions.forEach(x=>put(`• ${x}`));put('FONTES PÚBLICAS E STATUS DA CONSULTA',true);result.sources.forEach(x=>{put(`[${x.id}] ${x.name} — ${x.checked?'consulta online realizada':'link para verificação; consulta não confirmada'}`);put(x.url)});
 put('FONTES PRIVADAS IDENTIFICADAS NO CASO',true);(result.knowledgeReferences||[]).forEach(x=>put(`[${x.id}] ${x.sourceId}${x.sourcePage?', '+x.sourcePage:''} – ${x.title} (${x.status})`));put('Os documentos bancários originais, saldos atualizados e a avaliação profissional prevalecem sobre esta análise.');doc.save('Plano_Justo_Analise_Documental_IA.pdf');}
export default function DossierIntelligence({model,record,session,db,dirty,demoMode}){
 const [focus,setFocus]=useState('global'),[question,setQuestion]=useState(''),[consent,setConsent]=useState(false),[consultOfficial,setConsultOfficial]=useState(true),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[result,setResult]=useState(null),[downloading,setDownloading]=useState(false);
 const findings=useMemo(()=>strategicFindings(model),[model]);const options=[{id:'global',name:'Plano completo'},{id:'itau_cons',name:'Itaú – consignado'},...model.debts.filter(d=>d.mode==='included').map(d=>({id:d.id,name:d.creditor}))];
 const disabled=demoMode||!record?.id||!session?.user||!db||dirty||busy||!consent;
 async function analyze(){if(disabled)return;setBusy(true);setStatus('');setResult(null);try{const {data:{session:current},error}=await db.auth.getSession();if(error||!current?.access_token)throw Error('Sessão expirada: entre novamente.');const r=await fetch('/api/dossier-ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${current.access_token}`},body:JSON.stringify({caseId:record.id,focus,question,consultOfficial,consent:true})});const x=await r.json();if(!r.ok)throw Error(x.error||'Não foi possível consultar a IA');setResult(x);setStatus(x.savedToHistory?'Análise gerada. O resumo foi registrado no histórico do chat.':'Análise gerada. O registro no histórico não pôde ser confirmado. Baixe o PDF.')}catch(err){setStatus(err.message||'A análise não foi concluída.')}finally{setBusy(false)}}
 return <section className="panel" id="dossier-ai"><div className="section-head"><div><h3>✦ Inteligência do dossiê</h3><p>Analisa evidências, pesquisa referências oficiais disponíveis e propõe providências para tornar a proposta mais fundamentada. Não altera valores por conta própria.</p></div></div>
  <div className="alert blue"><b>Diagnóstico automático, sem IA generativa</b><p>{findings.issues.filter(x=>x.severity==='critical').length} ponto(s) de atenção financeira e {findings.issues.filter(x=>x.severity==='warning').length} pendência(s) de documentação. A investigação abaixo é individualizada e exige sua autorização.</p></div>
  <div className="formgrid"><label>Escopo da análise<select value={focus} onChange={e=>setFocus(e.target.value)}>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Consultar fontes oficiais na internet<select value={consultOfficial?'yes':'no'} onChange={e=>setConsultOfficial(e.target.value==='yes')}><option value="yes">Sim – tentar atualizar as fontes</option><option value="no">Não – usar apenas dados do caso</option></select></label></div>
  <label className="dossier-choice">Pergunta específica (opcional)<textarea maxLength={1200} rows={3} placeholder="Ex.: quais documentos e argumentos faltam para sustentar a parcela do Itaú sem contar o consignado em paralelo?" value={question} onChange={e=>setQuestion(e.target.value)}/></label>
  <label className="check dossier-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Autorizo enviar meu resumo financeiro e trechos da memória processual (incluindo nomes e atos documentados de representantes) ao provedor de IA para esta análise. A consulta aos sites oficiais usa perguntas e links gerais, sem meus dados pessoais.</label>
  {demoMode?<div className="alert amber">A demonstração não envia dados à IA. Entre na sua conta e salve o caso para analisar seu dossiê pessoal.</div>:dirty?<div className="alert amber">Existem alterações não salvas. Clique em <b>Salvar alterações</b> antes de analisar, para que a IA use os mesmos valores do banco.</div>:!record?.id?<div className="alert amber">Importe seu backup e salve o caso na sua conta antes de analisar.</div>:null}
  <div className="export-actions"><button className="primary" disabled={disabled} onClick={analyze}>{busy?'Consultando e analisando...':'✦ Analisar dossiê com IA'}</button>{result&&<button className="ghost" disabled={downloading} onClick={async()=>{setDownloading(true);try{await downloadAnalysis(result)}catch(err){setStatus(err.message)}finally{setDownloading(false)}}}>↓ Baixar análise da IA em PDF</button>}</div>
  {status&&<div role="status" className="alert blue" style={{marginTop:12}}>{status}</div>}
  {result&&<div className="dossier-ai-result" aria-live="polite"><h4>Síntese para conferência humana</h4><p>{result.report.summary}</p><h4>Aspectos a documentar e discutir</h4><div className="dossier-facts">{result.report.priorities.map((x,i)=><article key={i} className="dossier-item"><b>{x.topic}</b><span className="dossier-ai-status">{STATUS[x.status]||'Conferir'}</span><p>{x.why}</p><p><b>Prova necessária:</b> {x.evidence}</p>{x.sourceIds.length>0&&<small>Fontes oficiais consultadas: {x.sourceIds.join(', ')}</small>}{!!x.caseSourceIds?.length&&<small className="case-cites"><b>Atos/documentos do caso:</b> {x.caseSourceIds.map(id=><span key={id}>{id}</span>)}</small>}</article>)}</div><h4>Fundamentação por credor</h4>{result.report.creditorStrategy.map((x,i)=><article key={i} className="alert blue"><b>{x.creditor}</b><p>{x.factualArgument}</p><p><b>Providência:</b> {x.request}</p><p><b>Limite/ressalva:</b> {x.caveat}</p>{!!x.caseSourceIds?.length&&<p className="case-cites"><b>Fontes privadas: </b>{x.caseSourceIds.join(', ')}</p>}</article>)}<h4>O que os atos processuais efetivamente registram</h4>{(result.report.proceduralReading||[]).map((x,i)=><article className="alert blue" key={i}><b>{x.documentedAct}</b><p>{x.implication}</p><small>Documentos: {x.caseSourceIds.join(', ')||'Sem documento identificado'}</small></article>)}<h4>Questões para avaliar com advogado</h4>{result.report.lawyerQuestions.map((x,i)=><p key={i}>{i+1}. {x}</p>)}<h4>Cuidados e incertezas</h4>{result.report.cautions.map((x,i)=><div className="alert amber" key={i}>{x}</div>)}<h4>Fontes e situação da consulta</h4><div className="official-sources">{result.sources.map(x=><div key={x.id}><b>{x.id}</b> <a href={x.url} target="_blank" rel="noreferrer">{x.name} ↗</a> <small>{x.checked?`Consultado em ${new Date(x.checkedAt).toLocaleString('pt-BR')}`:'Link para conferência — sem verificação online nesta análise'}</small></div>)}</div><p className="muted">Esta análise não garante acordo nem homologação. Revise com os originais e o profissional responsável. O botão de análise não modifica as parcelas, o saldo ou documentos.</p></div>}
  {!result&&<div className="official-sources" style={{marginTop:18}}>{OFFICIAL_RESEARCH_SOURCES.map(s=><div key={s.id}><b>{s.id}</b> <a href={s.url} rel="noreferrer" target="_blank">{s.name} ↗</a></div>)}</div>}
 </section>;
}