/** Documental-grade exports. Arithmetic always comes from shared engine, not AI prose. */
import {brl} from '../../shared/engine.mjs';
import {makeReport,workbookSheets,exportFileName} from '../../shared/report-data.mjs';
const safe=x=>String(x??'').replace(/[\u0000-\u001f]/g,' ').replace(/[–—]/g,' - ').replace(/[•]/g,'-').trim();
const asMoney=x=>x==null?'A confirmar':brl(x);
const NAVY=[23,42,71],BLUE=[36,83,146],LIGHT=[239,244,250],INK=[37,54,78],MUTED=[99,114,136];

async function pdfBase(header,subtitle){
 const {jsPDF}=await import('jspdf');const {autoTable}=await import('jspdf-autotable');
 const doc=new jsPDF({unit:'mm',format:'a4',compress:true,putOnlyUsedFonts:true});let y=30;
 const page=(chapter='')=>{doc.addPage();y=27;doc.setFillColor(...NAVY);doc.rect(0,0,210,13,'F');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(255,255,255);doc.text('PLANO JUSTO  |  MEMÓRIA TÉCNICA',15,8);doc.setTextColor(...INK);if(chapter)heading(chapter,15)};
 const ensure=(needed=20)=>{if(y+needed>275)page()};
 const heading=(text,size=12)=>{ensure(20);doc.setTextColor(...NAVY);doc.setFont('helvetica','bold');doc.setFontSize(size);let lines=doc.splitTextToSize(safe(text),180);doc.text(lines,15,y);y+=lines.length*6+4;doc.setDrawColor(208,220,237);doc.line(15,y-2,195,y-2)};
 const paragraph=(value,{muted=false,bold=false}={})=>{const text=safe(value);if(!text)return;doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(9.2);doc.setTextColor(...(muted?MUTED:INK));const lines=doc.splitTextToSize(text,180);let i=0;while(i<lines.length){ensure(6);const n=Math.min(lines.length-i,Math.max(1,Math.floor((275-y)/4.8)));doc.text(lines.slice(i,i+n),15,y);y+=n*4.8+3;i+=n;}y+=1};
 const table=(columns,rows,{widths,styles={},fontSize=8}={})=>{ensure(25);autoTable(doc,{startY:y,head:[columns.map(safe)],body:rows.length?rows.map(row=>row.map(v=>typeof v==='number'?asMoney(v):safe(v))):[['Nenhum dado disponível neste período']],theme:'grid',margin:{left:15,right:15,top:22,bottom:21},styles:{font:'helvetica',fontSize,cellPadding:2.5,textColor:INK,overflow:'linebreak',valign:'top',lineColor:[226,231,239],lineWidth:.15,...styles},headStyles:{fillColor:NAVY,textColor:255,fontStyle:'bold',fontSize:8},alternateRowStyles:{fillColor:[247,250,253]},columnStyles:widths||{},showHead:'everyPage',didDrawPage:({settings})=>{if(doc.internal.getCurrentPageInfo().pageNumber>1){doc.setFillColor(...NAVY);doc.rect(0,0,210,13,'F');doc.setFontSize(8);doc.setTextColor(255,255,255);doc.text('PLANO JUSTO  |  MEMÓRIA TÉCNICA',15,8)}}});y=doc.lastAutoTable.finalY+8;};
 const badge=(text)=>{ensure(14);doc.setFillColor(...LIGHT);doc.roundedRect(15,y-4,180,11,2,2,'F');doc.setFontSize(8);doc.setTextColor(...BLUE);doc.setFont('helvetica','bold');doc.text(safe(text).slice(0,115),19,y+2);y+=14};
 doc.setFillColor(...NAVY);doc.rect(0,0,210,13,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('PLANO JUSTO  |  MEMÓRIA TÉCNICA',15,8);
 heading(header,16);paragraph(subtitle,{muted:true});
 const save=(filename)=>{const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(218,225,235);doc.line(15,282,195,282);doc.setFont('helvetica','normal');doc.setFontSize(7.4);doc.setTextColor(...MUTED);doc.text('MINUTA PARA CONFERÊNCIA DOCUMENTAL - NÃO É PETIÇÃO OU LAUDO',15,287);doc.text(`${i} / ${pages}`,195,287,{align:'right'});}doc.save(filename);return filename;};
 return {doc,page,heading,paragraph,table,badge,save};
}
function intro(r){const {model,calc}=r;return [
 `Interessado: ${model.profile.name||'A identificar'} | Processo: ${model.profile.case||'a confirmar'} | Unidade: ${model.profile.court||'a confirmar'}.`,
 `Data de emissão: ${r.asOf}. Primeiro vencimento solicitado: ${calc.requestedStart}. Prazo previsto na simulação: ${model.plan.months} meses. Não há presunção de homologação, adesão dos credores ou suspensão automática de consignação.`,
 `O demonstrativo expõe a capacidade econômica declarada e as bases negociais ainda sujeitas a conferência. As cotações históricas e as somas nominais de prestações futuras não são saldos atuais de quitação.`
]}
function moneyRows(r){const f=r.calc.finance;return [
 ['Disponibilidade líquida em dinheiro, após consignado',f.cashReceived],
 ['Despesas correntes que exigem dinheiro',f.cashBudget],
 ['Resultado mensal atual antes das demais dívidas',f.currentGap],
 ['Desconto consignado atual',r.model.consignado.installment],
 ['Parcela global oferecida',r.model.plan.monthly],
 ['Sobra estimada após substituição efetiva e proposta',f.afterProposal],
 ['Reserva financeira pretendida',r.model.plan.reserve],
 ]}
const creditorRows=r=>r.calc.allocations.map(x=>[x.creditor,asMoney(x.base),asMoney(x.monthly),asMoney(x.paid),asMoney(x.ending)]);
function disclaimer(r){return r.calc.totalEnding>.01?`ATENÇÃO: Esta simulação mantém saldo residual de ${brl(r.calc.totalEnding)}. O abatimento depende de composição, revisão devidamente demonstrada ou reestruturação legalmente cabível. Não apresentar esta versão como quitação compulsória integral.`:'Os saldos foram modelados até o fim do prazo, sem dispensar conferência de bases, taxas e documentos atualizados.'}
export async function downloadGeneralPdf(input){const r=makeReport(input),p=await pdfBase('PROPOSTA GLOBAL DE REPACTUAÇÃO','Memorial técnico, base financeira, justificativas individualizadas e anexos de conferência');
 p.badge('MATERIAL PARA AVALIAÇÃO JURÍDICA  |  DADOS E PROPOSTA SUJEITOS À CONFERÊNCIA');
 p.heading('1. Identificação e objeto');intro(r).forEach(x=>p.paragraph(x));
 p.heading('2. Síntese econômico-financeira');p.table(['Indicador','Valor'],moneyRows(r).map(([a,b])=>[a,asMoney(b)]),{widths:{0:{cellWidth:130},1:{cellWidth:50,halign:'right'}}});
 p.paragraph('A proposta depende de implementação formal da readequação do desconto consignado. O benefício de alimentação é analisado separadamente do dinheiro disponível. Rubricas declaradas podem estar sujeitas à avaliação específica no processo.');
 p.heading('3. Condições propostas');p.table(['Condição','Descrição'],[['Início',r.calc.requestedStart+' (solicitado, não deferido)'],['Prazo',r.model.plan.months+' meses, observado o limite de 60 meses'],['Parcela global',brl(r.model.plan.monthly)],['Total nominal projetado',brl(r.calc.totalPaid)],['Saldo residual ilustrativo',brl(r.calc.totalEnding)],['Consignado','Readequação/substituição sujeita a ato e implementação formal']],{widths:{0:{cellWidth:57},1:{cellWidth:123}}});p.badge(disclaimer(r));
 p.heading('4. Distribuição preliminar por credor');p.table(['Credor','Base ref.','Parcela','Pago sim.','Saldo sim.'],creditorRows(r),{fontSize:7.7});
 p.page('5. Fundamentação por credor');for(const d of r.dossiers){p.heading(d.name,11);p.paragraph(`Base documental: ${d.source||'não informada'}. Os valores dependem de memória vigente e conferência com original.`,{muted:true});for(const x of d.lines){p.paragraph(x.title,{bold:true});p.paragraph(x.text)}if(d.warnings?.length){p.paragraph('Ressalvas documentais:',{bold:true});d.warnings.forEach(x=>p.paragraph('- '+x))}}
 p.page('6. Providências e documentos requisitados');for(const d of r.dossiers){p.heading(d.name,10);d.requests.forEach((x,i)=>p.paragraph(`${i+1}. ${x}`))}
 p.page('7. Anexo: evolução dos saldos e lançamentos');for(const d of r.dossiers){if(d.loan)continue;p.heading(d.name,11);const entries=(d.entries||[]);p.table(['Data','Natureza','Valor','Fonte / situação'],entries.map(x=>[x.date,x.kind,asMoney(x.amount),[x.description,x.status,x.source].filter(Boolean).join(' | ')]),{fontSize:7,widths:{0:{cellWidth:20},1:{cellWidth:34},2:{cellWidth:29},3:{cellWidth:97}}});}
 p.page('8. Anexo: cronograma de pagamento');p.paragraph('Cronograma ilustrativo baseado na prestação global informada, sujeito às bases definitivas, rateio, encargos pactuados e homologação. O detalhamento íntegro e editável integra a planilha Excel.');p.table(['Compet.','Credor','Saldo inicial','Pagamento','Saldo final'],r.calc.schedule.map(x=>[x.month,x.creditor,asMoney(x.opening),asMoney(x.payment),asMoney(x.ending)]),{fontSize:7.2,widths:{0:{cellWidth:21},1:{cellWidth:55},2:{cellWidth:35},3:{cellWidth:33},4:{cellWidth:36}}});
 p.page('9. Referências para verificação');r.sections.at(-1).body.forEach(x=>p.paragraph(x,{muted:true}));p.paragraph('Deverá acompanhar a documentação original, com datas-base uniformizadas. A análise jurídica e o protocolo cabem ao profissional habilitado.');return p.save(exportFileName('Memorial_Repactuacao_Completo','pdf'));
}
export async function downloadCreditorPdf(input,id){const r=makeReport(input),d=r.dossiers.find(x=>x.id===id);if(!d)throw new Error('Credor não encontrado.');const p=await pdfBase('MEMÓRIA INDIVIDUAL DO CREDOR',d.name+' | Demonstrativo e diligências para conciliação');p.badge('VALORES HISTÓRICOS / REFERENCIAIS - NÃO SÃO QUITAÇÃO ATUAL');p.heading('1. Identificação e objetivo');intro(r).forEach(x=>p.paragraph(x));p.heading('2. Composição e justificativas');d.lines.forEach(x=>{p.paragraph(x.title,{bold:true});p.paragraph(x.text)});p.heading('3. Lançamentos e evolução');p.table(['Competência','Tipo','Valor','Descrição / prova'],(d.entries||[]).map(x=>[x.date,x.kind,asMoney(x.amount),[x.description,x.source,x.status].filter(Boolean).join(' | ')]),{fontSize:7.4});p.heading('4. Informações e documentos a solicitar');d.requests.forEach((x,i)=>p.paragraph(`${i+1}. ${x}`));p.heading('5. Limites da conclusão');d.warnings.forEach(x=>p.paragraph('- '+x));p.paragraph('O relatório não reconhece automaticamente cobrança abusiva, desconto de principal ou pagamento ainda não apropriado.',{muted:true});return p.save(exportFileName('Memoria_'+id.replace(/[^a-z0-9_-]/gi,'_'),'pdf'))}
export async function downloadRequestsPdf(input){const r=makeReport(input),p=await pdfBase('RELAÇÃO DE DOCUMENTOS A REQUISITAR','Exibição contratual e reconciliação das operações, por credor');p.paragraph('Solicita-se documentação legível, atualizada, com número da operação, data-base, taxas, encargos, pagamentos e memória de evolução. Esta lista não reconhece o saldo informado pelo banco.');for(const d of r.dossiers){p.heading(d.name,11);d.requests.forEach((x,i)=>p.paragraph(`${i+1}. ${x}`))}return p.save(exportFileName('Pedidos_Documentos_Credores','pdf'))}

const fieldNames={Resumo:'PAINEL EXECUTIVO',Credores:'COMPOSIÇÃO POR CREDOR',Consignado:'EMPRÉSTIMO CONSIGNADO',Lancamentos:'LANÇAMENTOS E FONTES',Conciliação:'RECONCILIAÇÃO DE FATURAS',Encargos:'COMPOSIÇÃO DOS ENCARGOS',Justificativas:'FUNDAMENTAÇÃO INDIVIDUAL',Providencias:'CRONOLOGIA DAS PROVIDÊNCIAS',Orcamento:'ORÇAMENTO FAMILIAR',Cronograma:'CRONOGRAMA DE PAGAMENTOS',Pendencias:'EXIGÊNCIAS A SUPRIR',Referencias:'FONTES DE CONSULTA'};
export async function downloadWorkbook(input){
 const ExcelMod=await import('exceljs/dist/exceljs.min.js');const ExcelJS=ExcelMod.default?.Workbook?ExcelMod.default:ExcelMod;const workbook=new ExcelJS.Workbook();workbook.creator='Plano Justo';workbook.title='Memória econômico-financeira para conciliação';workbook.subject='Proposta em 60 meses com fonte, data-base e ressalvas';workbook.calcProperties.fullCalcOnLoad=true;
 const raw=workbookSheets(input),r=makeReport(input);raw.Resumo=[['Indicador','Valor'],...raw.Resumo.slice(1)];const currencyKeys=/valor|saldo|base|fatura|juros|iof|multa|parcela|pago|pagamento|taxa|montante|despesa|renda|resultado|cobrado|encargos|compras|transfer[eê]ncias|gasto|benefício|mensal|nominal|total|principal/i;
 for(const [name,data] of Object.entries(raw)){
  const sheet=workbook.addWorksheet(name.slice(0,31),{views:[{state:'frozen',ySplit:5}],pageSetup:{paperSize:9,orientation:data[0]?.length>5?'landscape':'portrait',fitToPage:true,fitToWidth:1,fitToHeight:0},properties:{defaultRowHeight:19}});
  const width=Math.max(2,data[0]?.length||2);sheet.mergeCells(1,1,1,width);const title=sheet.getCell(1,1);title.value='PLANO JUSTO  /  '+(fieldNames[name]||name.toUpperCase());title.font={name:'Aptos Display',size:16,bold:true,color:{argb:'FFFFFFFF'}};title.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF172A47'}};title.alignment={vertical:'middle'};sheet.getRow(1).height=33;
  sheet.mergeCells(2,1,2,width);const sub=sheet.getCell(2,1);sub.value=`Data-base de emissão: ${r.asOf}   •   Minuta para conferência   •   Valores históricos não equivalem à cotação de hoje`;sub.font={name:'Aptos',size:10,italic:true,color:{argb:'FF385780'}};sub.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFEFF4FA'}};sheet.getRow(2).height=24;
  sheet.addRow([]);sheet.addRow(data[0]||[]);sheet.getRow(4).eachCell((c)=>{c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF28578C'}};c.font={name:'Aptos',color:{argb:'FFFFFFFF'},bold:true,size:10};c.alignment={vertical:'middle',wrapText:true};c.border={bottom:{style:'medium',color:{argb:'FF1D3B60'}}}});sheet.getRow(4).height=34;
  const nums=new Set();data.slice(1).forEach((row,i)=>{const sr=sheet.addRow(row.map(v=>typeof v==='string'&&/^[=+@]/.test(v)?"'"+v:v));const j=i+5;sr.height=21;sr.eachCell({includeEmpty:true},(c,k)=>{c.font={name:'Aptos',size:10,color:{argb:'FF263A55'}};c.alignment={vertical:'middle',wrapText:k===1||typeof c.value==='string'&&c.value.length>45};if(i%2===1)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF4F7FB'}};c.border={bottom:{style:'hair',color:{argb:'FFE6ECF2'}}};if(typeof c.value==='number'){nums.add(k);c.numFmt=currencyKeys.test(String(data[0]?.[k-1]||''))?'"R$ "#,##0.00;[Red]("R$ "#,##0.00)':'#,##0.00';c.alignment={vertical:'middle',horizontal:'right'};}if((name==='Credores'||name==='Consignado')&&k===1)c.font={name:'Aptos',size:10,bold:true,color:{argb:'FF214D81'}}});if(row.some(v=>typeof v==='string'&&v.length>110))sr.height=45;});
  sheet.columns=Array.from({length:width},(_,i)=>({width:i===0?38:(name==='Justificativas'&&i===2?75:name==='Lancamentos'&&[3,5].includes(i)?45:name==='Referencias'&&i===1?85:i===1?31:20)}));
  if(data.length>1){sheet.autoFilter={from:{row:4,column:1},to:{row:4+data.length-1,column:width}};}
  if(name==='Credores'&&data.length>1){const sum=sheet.addRow(Array(width).fill(''));sum.getCell(1).value='TOTAL PROJETADO';for(const k of [4,5,6,7,8]){const col=String.fromCharCode(64+k);sum.getCell(k).value={formula:`SUM(${col}5:${col}${sum.number-1})`};sum.getCell(k).numFmt='"R$ "#,##0.00;[Red]("R$ "#,##0.00)';}sum.eachCell({includeEmpty:true},c=>{c.font={name:'Aptos',bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF21466F'}}});sum.height=26;}
  if(name==='Resumo'){sheet.getColumn(1).width=61;sheet.getColumn(2).width=32;sheet.getCell('B5').font={name:'Aptos',bold:true,size:11,color:{argb:'FF214D81'}};}
  sheet.headerFooter.oddFooter.center.text='Plano Justo | Documento de trabalho | Página &P de &N';sheet.printTitleRows='1:4';
 }
 const bytes=await workbook.xlsx.writeBuffer();const blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const name=exportFileName('Plano_Economico_Financeiro','xlsx');const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return name;
}
export async function downloadAIAnalysis(result){const p=await pdfBase('PARECER DE APOIO DOCUMENTAL','Análise assistida por IA | Documento de trabalho para revisão do profissional responsável');
 p.badge('A ANÁLISE NÃO SUBSTITUI PROVAS OU INTERPRETAÇÃO PROFISSIONAL');p.heading('1. Escopo e proveniência');p.paragraph(`Emitido em ${new Date(result.generatedAt).toLocaleString('pt-BR')}. Versão do caso: ${result.caseVersion}. Provedor: ${result.provider||'não informado'}.`);p.paragraph('As afirmações dependem da correspondência entre os identificadores citados, as fontes efetivamente lidas e os originais. Hipóteses e pedidos não são decisões já tomadas.');
 p.heading('2. Síntese técnica');p.paragraph(result.report.summary);p.heading('3. Pontos de atenção e comprovação');p.table(['Tema','Análise e prova necessária','Situação'],(result.report.priorities||[]).map(x=>[x.topic,[x.why,x.evidence,`Fontes: ${(x.sourceIds||[]).concat(x.caseSourceIds||[]).join(', ')||'pendentes'}`].join('\n'),x.status]),{fontSize:7.7,widths:{0:{cellWidth:42},1:{cellWidth:110},2:{cellWidth:28}}});
 p.page('4. Fundamentação por credor');(result.report.creditorStrategy||[]).forEach(x=>{p.heading(x.creditor,11);p.paragraph('Argumento factual: '+x.factualArgument);p.paragraph('Providência: '+x.request);p.paragraph('Limite da alegação: '+x.caveat);p.paragraph('Documentos: '+(x.caseSourceIds||[]).join(', '),{muted:true});});
 p.page('5. Contrapontos e respostas condicionais');(result.report.opposingPoints||[]).forEach(x=>{p.heading(x.argument,10);p.paragraph('Objeção que merece preparo: '+x.possibleObjection);p.paragraph('Resposta se houver comprovação: '+x.answerIfDocumented);p.paragraph('Prova necessária: '+x.proofNeeded)});
 p.page('6. Atos documentados e providências');(result.report.proceduralReading||[]).forEach(x=>{p.paragraph(x.documentedAct,{bold:true});p.paragraph(x.implication);p.paragraph('Documentos: '+(x.caseSourceIds||[]).join(', '),{muted:true})});p.table(['Providência','Responsável','Dependência e entrega'],(result.report.actionPlan||[]).map(x=>[x.task,x.responsible,[x.dependency,x.deliverable].join(' / ')]),{fontSize:7.7});
 p.page('7. Controle de fontes');p.table(['ID','Fonte pública','Estado'],(result.sources||[]).map(x=>[x.id,x.name+'\n'+x.url,x.checked?'Consultada nesta execução':'Não confirmada']),{fontSize:7.5,widths:{0:{cellWidth:17},1:{cellWidth:128},2:{cellWidth:35}}});p.heading('Ressalvas finais');(result.report.cautions||[]).forEach(x=>p.paragraph('- '+x));return p.save(exportFileName('Analise_Assistida_Para_Revisao','pdf'))}