import {brl} from '../../shared/engine.mjs';
import {makeReport,workbookSheets,exportFileName} from '../../shared/report-data.mjs';

const plain=s=>String(s??'').replace(/[\u0000-\u001f]/g,' ').replace(/[—–]/g,'-').replace(/[“”]/g,'"').replace(/•/g,'-').trim();
const safeSheet=s=>plain(s).slice(0,31)||'Planilha';
const money=v=>Number.isFinite(Number(v))?brl(Number(v)):'Pendente';
const palette={navy:[19,43,78],blue:[35,92,180],light:[241,246,253],ink:[34,49,73],muted:[102,117,138],amber:[255,248,230],green:[232,248,238],red:[255,239,237]};

async function pdfKit(){const [{jsPDF},auto]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);return {jsPDF,autoTable:auto.default||auto};}
function addHeaderFooter(doc,title){const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFillColor(...palette.navy);doc.rect(0,0,210,8,'F');doc.setDrawColor(221,228,238);doc.line(14,282,196,282);doc.setFont('helvetica','normal');doc.setTextColor(...palette.muted);doc.setFontSize(7.5);doc.text('Plano Justo - documento técnico de trabalho. Conferir valores atuais e documentos originais.',14,287);doc.text(`${i}/${pages}`,190,287,{align:'right'});if(i>1){doc.setFont('helvetica','bold');doc.setTextColor(...palette.ink);doc.setFontSize(8);doc.text(title,14,14);}}}
function h2(doc,text,y){doc.setTextColor(...palette.navy);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(plain(text),14,y);return y+7;}
function para(doc,text,y,{bold=false,size=9,color=palette.ink}={}){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);doc.setTextColor(...color);const rows=doc.splitTextToSize(plain(text),182);if(y+rows.length*4.6>274){doc.addPage();y=21;}doc.text(rows,14,y);return y+rows.length*4.6+3;}
function callout(doc,title,text,y,type='blue'){const bg=type==='amber'?palette.amber:type==='red'?palette.red:palette.light;const border=type==='amber'?[230,183,87]:type==='red'?[220,120,110]:[175,201,237];const rows=doc.splitTextToSize(plain(text),172),h=Math.max(18,10+rows.length*4.1);if(y+h>274){doc.addPage();y=21;}doc.setFillColor(...bg);doc.setDrawColor(...border);doc.roundedRect(14,y,182,h,2,2,'FD');doc.setFont('helvetica','bold');doc.setTextColor(...palette.navy);doc.setFontSize(8.5);doc.text(plain(title).toUpperCase(),19,y+6);doc.setFont('helvetica','normal');doc.setTextColor(...palette.ink);doc.setFontSize(8.5);doc.text(rows,19,y+11);return y+h+5;}
async function table(doc,autoTable,head,body,y,widths={}){if(y>257){doc.addPage();y=21;}autoTable(doc,{startY:y,head:[head.map(plain)],body:body.map(row=>row.map(v=>typeof v==='number'?v:plain(v))),theme:'grid',styles:{font:'helvetica',fontSize:7.4,textColor:palette.ink,cellPadding:2.2,lineColor:[220,227,237],lineWidth:.2,overflow:'linebreak'},headStyles:{fillColor:palette.navy,textColor:[255,255,255],fontStyle:'bold'},alternateRowStyles:{fillColor:[248,250,253]},columnStyles:widths,margin:{left:14,right:14},didDrawPage:()=>{}});return doc.lastAutoTable.finalY+6;}

function executiveRows(r){const {model,calc}=r;return [
 ['Renda em dinheiro após consignado',money(calc.finance.cashReceived)],['Despesas mensais em dinheiro',money(calc.finance.cashBudget)],['Resultado atual',money(calc.finance.currentGap)],['Parcela global proposta',money(model.plan.monthly)],['Prazo proposto',`${model.plan.months} meses`],['Início solicitado',calc.requestedStart],['Base referencial total',money(calc.baseTotal)],['Total projetado no plano',money(calc.totalPaid)],['Saldo residual ilustrativo',money(calc.totalEnding)]
];}
export async function downloadGeneralPdf(input){const r=makeReport(input),{model,calc}=r,{jsPDF,autoTable}=await pdfKit();const doc=new jsPDF({unit:'mm',format:'a4',compress:true});
 doc.setFillColor(...palette.navy);doc.rect(0,0,210,297,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(25);doc.text('PLANO JUSTO',18,46);doc.setFontSize(16);doc.text('Proposta global de repactuação e memória de cálculo',18,58);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(211,224,245);doc.text(`Processo: ${plain(model.profile.case||'a informar')}`,18,76);doc.text(`${plain(model.profile.court||'TJDFT')} | emissão ${r.asOf}`,18,84);doc.setFontSize(9);doc.text('Documento de trabalho para conciliação e revisão jurídica. Não substitui petição, perícia ou decisão judicial.',18,104,{maxWidth:165});doc.setDrawColor(85,130,195);doc.line(18,119,192,119);doc.setFontSize(8.5);doc.text('Premissa central: nenhum saldo histórico é tratado como quitação atual sem documento do credor e data-base vigente.',18,130,{maxWidth:165});
 doc.addPage();let y=22;y=h2(doc,'1. Síntese executiva',y);y=await table(doc,autoTable,['Indicador','Valor'],executiveRows(r),y,{0:{cellWidth:105},1:{cellWidth:65}});
 y=callout(doc,'Leitura essencial',calc.totalEnding>0?`A oferta global de ${money(model.plan.monthly)} por ${model.plan.months} meses soma ${money(calc.totalPaid)} e, usando as bases referenciais hoje cadastradas, deixa saldo residual ilustrativo de ${money(calc.totalEnding)}. Portanto, este cenário deve ser apresentado como proposta consensual sujeita a negociação e reconciliação documental, não como quitação compulsória garantida.`:'A simulação não apresenta saldo residual, mas ainda depende de atualização dos demonstrativos e enquadramento jurídico.',y,calc.totalEnding>0?'amber':'blue');
 y=callout(doc,'Condição de viabilidade',`O orçamento atual registra ${money(calc.finance.currentGap)} antes das demais dívidas. O cenário de parcela global só é economicamente viável se o desconto do consignado for efetivamente coordenado/substituído conforme acordo ou ato formal; não se deve somar a nova parcela ao desconto integral de ${money(model.consignado.installment)}.`,y,'blue');
 y=h2(doc,'2. Estrutura da proposta por credor',y);const alloc=calc.allocations.map(a=>[a.creditor,money(a.base),money(a.monthly),money(a.required),money(a.paid),money(a.ending),a.verified?'Verificado':'Atualizar']);y=await table(doc,autoTable,['Credor','Base ref.','Parcela prop.','Necessário s/ abat.','Total 60m','Residual','Status'],alloc,y,{0:{cellWidth:45},1:{cellWidth:24},2:{cellWidth:23},3:{cellWidth:25},4:{cellWidth:23},5:{cellWidth:23},6:{cellWidth:20}});
 y=para(doc,'“Necessário s/ abat.” é apenas a divisão aritmética da base a juros zero pelo prazo do plano. Não substitui cálculo jurídico do principal corrigido, nem incorpora eventual composição consensual.',y,{size:8,color:palette.muted});
 y=h2(doc,'3. Fundamentação financeira da capacidade',y);const fin=[['Salário bruto',money(calc.finance.gross)],['Líquido em dinheiro após consignado',money(calc.finance.cashReceived)],['Benefício alimentação informado',money(model.payroll.foodBenefit)],['Despesas em dinheiro',money(calc.finance.cashBudget)],['Resultado atual',money(calc.finance.currentGap)],['Disponibilidade condicional sem desconto atual',money(calc.finance.conditionalAvailable)],['Resultado condicional após parcela global',money(calc.finance.afterProposal)],['Reserva desejada',money(model.plan.reserve)]];y=await table(doc,autoTable,['Componente','Valor'],fin,y,{0:{cellWidth:110},1:{cellWidth:55}});
 y=para(doc,'O benefício alimentação deve permanecer separado do dinheiro disponível, para evitar inflar artificialmente a capacidade de pagamento. Despesas contestáveis devem ser declaradas com transparência e tratadas juridicamente, não ocultadas.',y,{size:8.5});
 y=h2(doc,'4. Credor por credor: fatos, justificativa e documentos',y);
 for(const d of r.dossiers){if(y>235){doc.addPage();y=21;}y=para(doc,d.name,y,{bold:true,size:11,color:palette.navy});for(const line of d.lines||[])y=para(doc,`${line.title}: ${line.text}`,y,{size:8.7});if(d.requests?.length){y=para(doc,'Documentos/explicações a exigir:',y,{bold:true,size:8.8});for(const q of d.requests)y=para(doc,'- '+q,y,{size:8.3});}for(const w of d.warnings||[])y=callout(doc,'Ressalva',w,y,'amber');}
 y=h2(doc,'5. Pontos jurídicos que condicionam a proposta',y);y=para(doc,'Fase consensual: o consumidor apresenta proposta global, preservando mínimo existencial e buscando solução conjunta. O valor pode refletir concessões negociadas pelos credores.',y);y=para(doc,'Fase judicial compulsória: a Lei do Superendividamento exige, entre outros requisitos, assegurar no mínimo o principal devido corrigido e liquidação no prazo legal; portanto, um desconto consensual pretendido não pode ser tratado como direito previamente reconhecido.',y);y=para(doc,'Cartões: a análise do teto de juros/encargos deve ser feita por operação de rotativo/parcelamento, com valor original, datas e encargos discriminados no DDC, e não por simples comparação entre o total da fatura e as compras do mês.',y);
 y=h2(doc,'6. Checklist antes de apresentar',y);const checks=['Atualizar DDC/saldo devedor e cotação de liquidação do consignado.','Obter DDC de cartão e faturas integrais do Santander, separando cada operação de rotativo/parcelamento.','Conciliar todos os pagamentos e transferências sem dupla contagem.','Atualizar saldos de Itaú cartão, BRB e PicPay.','Confirmar o enquadramento das dívidas pendentes/excluídas e garantias.','Anexar orçamento atual e comprovantes de renda/despesas relevantes.','Recalcular a proposta após as informações exigidas aos credores e antes da audiência.','Revisar a redação final com advogado responsável pelo caso.'];y=await table(doc,autoTable,['#','Providência'],checks.map((x,i)=>[i+1,x]),y,{0:{cellWidth:12},1:{cellWidth:155}});
 y=h2(doc,'7. Referências oficiais',y);const refs=[['CDC - arts. 104-A e 104-B','https://planalto.gov.br/ccivil_03/leis/l8078compilado.htm'],['Banco Central - DDC empréstimos','https://www.bcb.gov.br/meubc/faqs/p/documento-descritivo-do-credito-ddc'],['Banco Central - DDC cartão','https://www.bcb.gov.br/meubc/faqs/p/documento-descritivo-do-credito-ddc-para-as-operacoes-com-cartao-de-credito'],['Ministério da Justiça - Superendividamento','https://www.gov.br/mj/pt-br/assuntos/seus-direitos/consumidor/defesadoconsumidor/Superendividamento']];y=await table(doc,autoTable,['Fonte','Endereço'],refs,y,{0:{cellWidth:65},1:{cellWidth:105}});addHeaderFooter(doc,'Plano Justo - Proposta global e memória');const filename=exportFileName('Proposta_Global_Profissional','pdf');doc.save(filename);return filename;}

export async function downloadCreditorPdf(input,id){const r=makeReport(input),d=r.dossiers.find(x=>x.id===id);if(!d)throw new Error('Credor não encontrado.');const {jsPDF,autoTable}=await pdfKit();const doc=new jsPDF({unit:'mm',format:'a4',compress:true});let y=22;y=h2(doc,`Memorial individual - ${d.name}`,y);y=para(doc,`Data de emissão: ${r.asOf}. Valores históricos ou referenciais não representam quitação atual sem documento vigente.`,y);const a=d.allocation;y=await table(doc,autoTable,['Base ref.','Parcela proposta','Pago no prazo','Residual'],[[money(a?.base),money(a?.monthly),money(a?.paid),money(a?.ending)]],y);for(const x of d.lines||[])y=para(doc,`${x.title}: ${x.text}`,y,{size:9});y=h2(doc,'Documentos e esclarecimentos necessários',y);y=await table(doc,autoTable,['#','Item'],(d.requests||[]).map((x,i)=>[i+1,x]),y,{0:{cellWidth:12},1:{cellWidth:155}});if(d.entries?.length){y=h2(doc,'Lançamentos registrados',y);y=await table(doc,autoTable,['Data','Tipo','Valor','Descrição','Status'],d.entries.map(x=>[x.date||'-',x.kind,money(x.amount),x.description,x.status]),y,{0:{cellWidth:22},1:{cellWidth:30},2:{cellWidth:25},3:{cellWidth:78},4:{cellWidth:28}});}addHeaderFooter(doc,`Memorial individual - ${d.name}`);const filename=exportFileName('Credor_'+id.replace(/[^A-Za-z0-9_-]+/g,'_'),'pdf');doc.save(filename);return filename;}
export async function downloadRequestsPdf(input){const r=makeReport(input),{jsPDF,autoTable}=await pdfKit();const doc=new jsPDF({unit:'mm',format:'a4'});let y=22;y=h2(doc,'Solicitação consolidada de documentos aos credores',y);y=para(doc,'Finalidade: conferir saldo, principal, encargos, pagamentos, prazo e condições de cada operação antes da consolidação do plano. Não constitui reconhecimento do valor atualmente cobrado.',y);for(const d of r.dossiers){if(y>245){doc.addPage();y=21;}y=para(doc,d.name,y,{bold:true,size:10.5,color:palette.navy});y=await table(doc,autoTable,['#','Documento/informação'],(d.requests||[]).map((x,i)=>[i+1,x]),y,{0:{cellWidth:12},1:{cellWidth:155}});}addHeaderFooter(doc,'Solicitação consolidada de documentos');const filename=exportFileName('Pedidos_Aos_Credores','pdf');doc.save(filename);return filename;}

function setCol(sheet,widths){widths.forEach((w,i)=>sheet.getColumn(i+1).width=w)}
function styleHeader(row){row.height=24;row.eachCell(cell=>{cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF132B4E'}};cell.font={bold:true,color:{argb:'FFFFFFFF'},size:10};cell.alignment={vertical:'middle',wrapText:true};cell.border={bottom:{style:'thin',color:{argb:'FF93A4BC'}}};});}
function styleTitle(sheet,title,subtitle,cols){sheet.mergeCells(1,1,1,cols);let c=sheet.getCell(1,1);c.value=title;c.font={bold:true,size:20,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF132B4E'}};c.alignment={vertical:'middle'};sheet.getRow(1).height=34;sheet.mergeCells(2,1,2,cols);c=sheet.getCell(2,1);c.value=subtitle;c.font={size:10,color:{argb:'FF51657F'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF1F6FD'}};c.alignment={vertical:'middle',wrapText:true};sheet.getRow(2).height=28;}
export async function downloadWorkbook(input){const ExcelJS=(await import('exceljs')).default||await import('exceljs');const r=makeReport(input),{model,calc}=r,wb=new ExcelJS.Workbook();wb.creator='Plano Justo';wb.created=new Date();wb.properties.date1904=false;
 const summary=wb.addWorksheet('Resumo Executivo',{views:[{state:'frozen',ySplit:4}]});styleTitle(summary,'PLANO JUSTO - MEMÓRIA FINANCEIRA','Modelo profissional para conciliação e revisão jurídica. Células amarelas indicam informação a atualizar.',7);summary.addRow([]);summary.addRow(['Indicador','Valor','Leitura','Fonte/observação']);styleHeader(summary.getRow(4));const sr=executiveRows(r);sr.forEach(([a,b])=>summary.addRow([a,b,a==='Saldo residual ilustrativo'?(calc.totalEnding>0?'Requer negociação/revisão; não tratar como remissão automática.':'Sem residual no modelo.'):'',a==='Base referencial total'?'Valores com datas-base distintas; atualizar DDCs.':'Motor Plano Justo']));setCol(summary,[38,22,56,55]);summary.eachRow((row,n)=>{if(n>4){row.alignment={vertical:'top',wrapText:true};if(n%2===1)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF8FAFD'}};}});summary.getColumn(2).numFmt='R$ #,##0.00;[Red]-R$ #,##0.00';
 const prop=wb.addWorksheet('Proposta por Credor',{views:[{state:'frozen',ySplit:4}]});styleTitle(prop,'PROPOSTA POR CREDOR','O rateio de R$ 1.000/mês é cenário consensual. Compare com a coluna “necessário sem abatimento”.',10);prop.addRow([]);prop.addRow(['Credor','Base referencial','Participação','Parcela proposta','Total 60 meses','Necessário/mês s/ abat.','Residual','Status','Fonte','Observação']);styleHeader(prop.getRow(4));calc.allocations.forEach(a=>prop.addRow([a.creditor,a.base,a.share,a.monthly,a.paid,a.required,a.ending,a.verified?'Verificado':'Atualizar',a.source,a.ending>0?'Base não liquidada integralmente pela proposta atual.':'']));setCol(prop,[42,18,14,18,18,22,18,14,52,44]);['B','D','E','F','G'].forEach(c=>prop.getColumn(c).numFmt='R$ #,##0.00;[Red]-R$ #,##0.00');prop.getColumn('C').numFmt='0.00%';prop.autoFilter={from:'A4',to:'J4'};prop.eachRow((row,n)=>{if(n>4){row.alignment={vertical:'top',wrapText:true};if(row.getCell(7).value>0)row.getCell(7).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFE9CC'}};}});
 const orc=wb.addWorksheet('Orçamento',{views:[{state:'frozen',ySplit:4}]});styleTitle(orc,'ORÇAMENTO FAMILIAR','Separação entre valor bruto da despesa, cobertura por benefício e saída efetiva de dinheiro.',7);orc.addRow([]);orc.addRow(['Despesa','Categoria','Valor bruto','Cobertura benefício','Saída em dinheiro','Tratamento','Fonte']);styleHeader(orc.getRow(4));model.budget.forEach(x=>orc.addRow([x.name,x.category,x.gross,x.ticket,Math.max(0,x.gross-x.ticket),x.kind,x.source]));orc.addRow(['TOTAL','','', '',{formula:`SUM(E5:E${orc.rowCount})`},'','']);setCol(orc,[38,22,18,20,18,18,52]);['C','D','E'].forEach(c=>orc.getColumn(c).numFmt='R$ #,##0.00');
 const itau=wb.addWorksheet('Itaú Consignado');styleTitle(itau,'ITAÚ CONSIGNADO - RECONSTRUÇÃO','A cotação de 04/08/2026 é histórica. Solicitar DDC e quitação atual antes de protocolar proposta.',5);itau.addRow([]);itau.addRow(['Elemento','Valor','Data-base','Interpretação','Fonte']);styleHeader(itau.getRow(4));const l=r.evidence.loan;[['Total financiado',l.originalFinanced,'Contrato','Principal + refinanciamentos/IOF a conferir',l.contractNote],['Crédito líquido recebido',l.cashReleased,'Contrato','Valor efetivamente liberado em conta',l.contractNote],['Contratos anteriores liquidados',l.priorSettled,'Contrato','Refinanciamentos incorporados',l.contractNote],['Total já pago',l.paidTotal,'Até 04/08/2026','13 parcelas/encargo conforme memorial',l.amortizationSource],['Principal amortizado',l.paidPrincipal,'Até 04/08/2026','Não confundir com total pago',l.amortizationSource],['Juros já pagos',l.paidInterest,'Até 04/08/2026','Histórico para reconstrução; não é crédito automático',l.amortizationSource],['Quitação informada',l.settlementAmount,l.settlementAsOf,'Cotação histórica; atualizar',l.settlementSource],['Parcelas nominais futuras',model.consignado.remaining*model.consignado.installment,l.settlementAsOf,'Fluxo nominal futuro ≠ quitação antecipada',model.consignado.source]].forEach(x=>itau.addRow(x));setCol(itau,[35,18,18,62,62]);itau.getColumn('B').numFmt='R$ #,##0.00';
 const san=wb.addWorksheet('Santander');styleTitle(san,'SANTANDER - EVOLUÇÃO E CONCILIAÇÃO','Separar compras, encargos discriminados, ajustes não explicados e pagamentos. Não presumir que diferença seja juro.',8);san.addRow([]);san.addRow(['Data','Natureza','Valor','Descrição','Status','Fonte','Operação','Conferência']);styleHeader(san.getRow(4));(r.evidence.ledgers.santander||[]).forEach(x=>san.addRow([x.date,x.kind,x.amount,x.description,x.status,x.source,x.operationId,x.status==='unreconciled'?'Solicitar discriminação':'Conferir original']));setCol(san,[14,20,16,58,18,58,20,28]);san.getColumn('C').numFmt='R$ #,##0.00';san.autoFilter={from:'A4',to:'H4'};
 const others=wb.addWorksheet('Demais Credores');styleTitle(others,'DEMAIS CREDORES','Saldos devem ser atualizados e reconciliados antes da versão final.',8);others.addRow([]);others.addRow(['Credor','Tipo','Cobrado/atual','Base','Data-base','Incluído?','Verificado?','Fonte']);styleHeader(others.getRow(4));model.debts.filter(d=>d.id!=='santander').forEach(d=>others.addRow([d.creditor,d.type,d.claim,d.base,d.asOf,d.mode,d.verified?'Sim':'Não',d.source]));setCol(others,[38,22,18,18,15,15,15,58]);['C','D'].forEach(c=>others.getColumn(c).numFmt='R$ #,##0.00');
 const cron=wb.addWorksheet('Cronograma 60M',{views:[{state:'frozen',ySplit:4}]});styleTitle(cron,'CRONOGRAMA DE 60 MESES','Cenário de rateio proporcional a juros negociados de 0% no motor. Não equivale a plano judicial compulsório aprovado.',7);cron.addRow([]);cron.addRow(['Competência','Mês','Credor','Saldo inicial','Juros simulados','Pagamento','Saldo final']);styleHeader(cron.getRow(4));calc.schedule.forEach(x=>cron.addRow([x.month,x.index,x.creditor,x.opening,x.interest,x.payment,x.ending]));setCol(cron,[15,9,42,18,18,18,18]);['D','E','F','G'].forEach(c=>cron.getColumn(c).numFmt='R$ #,##0.00');cron.autoFilter={from:'A4',to:'G4'};
 const check=wb.addWorksheet('Checklist Probatório');styleTitle(check,'CHECKLIST PROBATÓRIO','O objetivo é transformar alegações em pontos documentados antes da audiência/manifestação.',5);check.addRow([]);check.addRow(['Prioridade','Credor/Tema','Documento ou ação','Por que importa','Status']);styleHeader(check.getRow(4));[['Alta','Itaú consignado','DDC e cotação de quitação atual','Define principal/saldo e separa encargos futuros','Pendente'],['Alta','Santander','DDC do cartão e faturas integrais','Segrega cada operação de rotativo/parcelamento e encargos','Pendente'],['Alta','Todos','Sete campos exigidos na decisão','Permite comparar contratos em base homogênea','Pendente/Conferir'],['Alta','Orçamento','Contracheques e comprovantes atuais','Demonstra capacidade real e mínimo existencial','Atualizar'],['Média','Pagamentos Santander','Conciliação das transferências','Evita dupla contagem e demonstra boa-fé','Pendente'],['Média','Itaú/BRB/PicPay','Saldo atualizado e memória','Evita usar fatura histórica como saldo atual','Pendente']].forEach(x=>check.addRow(x));setCol(check,[14,28,52,62,20]);
 const fontes=wb.addWorksheet('Fontes');styleTitle(fontes,'FONTES E PREMISSAS','Links oficiais e documentos do caso devem ser conferidos na versão atual antes de qualquer protocolo.',4);fontes.addRow([]);fontes.addRow(['Tema','Fonte','URL','Uso no modelo']);styleHeader(fontes.getRow(4));[['CDC','Planalto','https://planalto.gov.br/ccivil_03/leis/l8078compilado.htm','Arts. 104-A/104-B e condições do plano'],['DDC empréstimos','Banco Central','https://www.bcb.gov.br/meubc/faqs/p/documento-descritivo-do-credito-ddc','Saldo, evolução, juros, prazo e amortização'],['DDC cartão','Banco Central','https://www.bcb.gov.br/meubc/faqs/p/documento-descritivo-do-credito-ddc-para-as-operacoes-com-cartao-de-credito','Operações de rotativo/parcelamento e encargos'],['Superendividamento','Ministério da Justiça','https://www.gov.br/mj/pt-br/assuntos/seus-direitos/consumidor/defesadoconsumidor/Superendividamento','Orientação institucional']].forEach(x=>fontes.addRow(x));setCol(fontes,[24,28,82,62]);
 for(const ws of wb.worksheets){ws.properties.defaultRowHeight=19;ws.eachRow(row=>row.alignment={...row.alignment,vertical:'top',wrapText:true});ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.25,right:.25,top:.5,bottom:.5,header:.2,footer:.2}};}
 const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=exportFileName('Memoria_Conciliação_Profissional','xlsx');a.click();URL.revokeObjectURL(url);return a.download;}

export async function downloadAIAnalysis(result){const {jsPDF,autoTable}=await pdfKit();const doc=new jsPDF({unit:'mm',format:'a4',compress:true});let y=22;const title='Plano Justo - análise fundamentada do dossiê';
 doc.setFillColor(...palette.navy);doc.rect(0,0,210,297,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(24);doc.text('PLANO JUSTO',18,46);doc.setFontSize(15);doc.text('Análise fundamentada do dossiê',18,58);doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.setTextColor(211,224,245);doc.text(`Gerada em ${new Date(result.generatedAt).toLocaleString('pt-BR')} | caso v${result.caseVersion}`,18,78);doc.text(`Provedor: ${plain(result.provider||'não informado')}`,18,86);doc.text('Documento técnico para revisão humana. Não é petição, perícia ou previsão de decisão.',18,106,{maxWidth:165});
 doc.addPage();y=22;y=h2(doc,'1. Síntese executiva',y);y=para(doc,result.report.summary,y,{size:10});y=h2(doc,'2. Pontos prioritários',y);y=await table(doc,autoTable,['Tema','Situação','Por que importa','Prova necessária'],(result.report.priorities||[]).map(x=>[x.topic,x.status,x.why,x.evidence]),y);
 y=h2(doc,'3. Revisão por especialidade',y);y=await table(doc,autoTable,['Lente','Achado','Próxima conferência','Fontes'],(result.report.specialistReviews||[]).map(x=>[String(x.lens).toUpperCase(),x.finding,x.nextCheck,[...(x.sourceIds||[]),...(x.caseSourceIds||[])].join(', ')||'Conferir']),y);
 y=h2(doc,'4. Fundamentação por credor',y);y=await table(doc,autoTable,['Credor','Argumento factual','Providência','Ressalva'],(result.report.creditorStrategy||[]).map(x=>[x.creditor,x.factualArgument,x.request,x.caveat]),y);
 y=h2(doc,'5. Atos processuais documentados',y);y=await table(doc,autoTable,['Ato','Implicação','Documento'],(result.report.proceduralReading||[]).map(x=>[x.documentedAct,x.implication,(x.caseSourceIds||[]).join(', ')||'Não indicado']),y);
 y=h2(doc,'6. Contrapontos e respostas condicionadas à prova',y);y=await table(doc,autoTable,['Argumento','Objeção possível','Resposta se comprovada','Prova'],(result.report.opposingPoints||[]).map(x=>[x.argument,x.possibleObjection,x.answerIfDocumented,x.proofNeeded]),y);
 y=h2(doc,'7. Plano de providências',y);y=await table(doc,autoTable,['#','Tarefa','Responsável','Dependência','Entrega'],(result.report.actionPlan||[]).map((x,i)=>[i+1,x.task,x.responsible,x.dependency,x.deliverable]),y);
 y=h2(doc,'8. Questões para revisão jurídica',y);for(const [i,x] of (result.report.lawyerQuestions||[]).entries())y=para(doc,`${i+1}. ${x}`,y);y=h2(doc,'9. Riscos e incertezas',y);for(const x of result.report.cautions||[])y=callout(doc,'Ponto a conferir',x,y,'amber');
 y=h2(doc,'10. Fontes públicas consultadas/indicadas',y);y=await table(doc,autoTable,['ID','Fonte','Situação','URL'],(result.sources||[]).map(x=>[x.id,x.name,x.checked?`Consultada em ${new Date(x.checkedAt).toLocaleString('pt-BR')}`:'Link para conferência',x.url]),y);y=h2(doc,'11. Documentos privados identificados',y);y=await table(doc,autoTable,['ID','Documento','Página','Status'],(result.knowledgeReferences||[]).map(x=>[x.id,x.sourceId||x.title,x.sourcePage||'-',x.status]),y);addHeaderFooter(doc,title);doc.save('Plano_Justo_Analise_Fundamentada_IA.pdf');return 'Plano_Justo_Analise_Fundamentada_IA.pdf';}