import {brl} from '../../shared/engine.mjs';
import {makeReport,workbookSheets,exportFileName} from '../../shared/report-data.mjs';

function printable(s){return String(s??'').replace(/[\u0000-\u001f]/g,' ').replace(/[—–]/g,'-').replace(/[“”]/g,'"').replace(/[•]/g,'-');}
const FILE_TAG=/[^A-Za-z0-9_-]+/g;
async function renderPdf(title,sections,filename){
 const {jsPDF}=await import('jspdf');const doc=new jsPDF({unit:'mm',format:'a4',compress:true});let y=17;const H=297;
 const newPage=()=>{doc.addPage();y=17};
 const line=(s,{size=10,bold=false,space=2}={})=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const ls=doc.splitTextToSize(printable(s),180);for(const x of ls){if(y>H-18)newPage();doc.text(x,15,y);y+=size/2.4}y+=space};
 doc.setFillColor(22,43,81);doc.rect(0,0,210,10,'F');line(title,{size:16,bold:true,space:5});
 for(const section of sections){if(y>H-41)newPage();line(section.title,{size:12,bold:true,space:4});for(const p of section.body||[])line(p,{size:9,space:3});}
 const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(104,118,142);doc.text(`Plano Justo | documento de trabalho | ${i}/${pages}`,15,288);}
 doc.save(filename);return filename;
}
export async function downloadGeneralPdf(input){const r=makeReport(input);const sections=[...r.sections];for(const d of r.dossiers)sections.push({title:`Dossiê: ${d.name}`,body:[...d.lines.map(x=>`${x.title}: ${x.text}`),'DOCUMENTOS A SOLICITAR:',...d.requests,...d.warnings.map(x=>`RESSALVA: ${x}`)]});sections.push({title:'Memória mensal por credor',body:r.calc.schedule.map(x=>`${x.month} | ${x.creditor} | inicial ${brl(x.opening)} | juros simulados ${brl(x.interest)} | pago ${brl(x.payment)} | final ${brl(x.ending)}`)});return renderPdf('Plano Justo - proposta, justificativas e memoria',sections,exportFileName('Dossie_Completo','pdf'));}
export async function downloadCreditorPdf(input,id){const r=makeReport(input),d=r.dossiers.find(x=>x.id===id);if(!d)throw new Error('Credor não encontrado.');const sections=[{title:'Identificação e status',body:[`Credor: ${d.name}. Data: ${r.asOf}. Fonte cadastrada: ${d.source||'pendente'}. Nenhum valor equivale a quitação atual se não houver data e documento vigente.`,...d.warnings]},{title:'Memória e justificativas',body:d.lines.map(x=>`${x.title}: ${x.text}`)},{title:'Itens históricos lançados (não necessariamente ciclo completo)',body:d.entries.length?d.entries.map(x=>`${x.date} | ${x.kind} | ${brl(x.amount)} | ${x.description} | ${x.status} | ${x.source}`):['Para este credor, a memória será detalhada assim que houver documentos.']},{title:'Requisições documentais',body:d.requests},{title:'Referências',body:r.sections.at(-1).body}];return renderPdf(`Plano Justo - ${d.name}`,sections,exportFileName('Credor_'+id.replace(FILE_TAG,'_'),'pdf'));}
export async function downloadRequestsPdf(input){const r=makeReport(input),sections=r.dossiers.map(d=>({title:d.name,body:d.requests}));sections.unshift({title:'Finalidade',body:['Solicitação de demonstrativos contratuais para conciliação financeira. Não representa reconhecimento do montante atualmente cobrado.','Pedir arquivo legível com data-base, taxas, pagamentos e referência do contrato/operação.']});return renderPdf('Solicitação de documentos por credor',sections,exportFileName('Pedidos_Aos_Credores','pdf'));}
export async function downloadWorkbook(input){const module=await import('xlsx'),XLSX=module.default||module;const wb=XLSX.utils.book_new();for(const [name,data] of Object.entries(workbookSheets(input))){const values=data.map(row=>row.map(v=>typeof v==='string'&&/^[=+@]/.test(v)?`'${v}`:v));const ws=XLSX.utils.aoa_to_sheet(values);ws['!cols']=(data[0]||[]).map((_,i)=>({wch:Math.min(i===0?38:43,i===0?38:43)}));ws['!autofilter']={ref:ws['!ref']};XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31));}const filename=exportFileName('Memoria_Concilicao','xlsx');XLSX.writeFile(wb,filename);return filename;}